### ISSUE TITLE
Ist es möglich bei Dienste die Option Mini Kids zu löschen?

### ISSUE THREAD

**Issue by staubthom** [szeberli/EGW-Webseite#101]
Ist es möglich bei Dienste die Option Mini Kids zu löschen? wir haben kein Mini Kids im EGW-Unterlangenegg

**Comment by szeberli** [comment]
Das ist so leider nicht möglich, da alle die selbe Grundstruktur haben.

**Comment by staubthom** [comment]
OK, kann geschlossen werden
