### ISSUE TITLE
Nicht nur registrierte Personen sondern auch einfach Namen erfassen 

### ISSUE THREAD

**Issue by staubthom** [szeberli/EGW-Webseite#103]
Generell wärs praktisch wenn die Eintragungen von Personen frei wählbar wären.
Bei den Diensten zum Beispiel bei der Kinderhüeti und bei Kidstreff wärs super, wenn man einfach einen Namen eintragen kann. Sonst müssen alle Eltern einen Account haben. Was wohl nie der Fall sein wird.

**Comment by szeberli** [comment]
Ist so nicht möglich
Du
Müsstest fiktive Benutzer anlegen.

**Comment by staubthom** [comment]
können wir machen, Fall schliessen
