### ISSUE TITLE
Agenda: Wochen-/Monatsansicht als Element zum Einbauen

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#108]
So wie ich das beurteile, ist die Agenda als Wochen-/Monats- oder Listenansicht immer eine eigene Seite. Könnte man diese Ansichten der Agenda nicht als Element zur Verfügung stellen, damit man diese in einer normalen Seite (wie die 3 Varianten des "Agenda Block") einbinden könnte? Dann wäre auch das Design mit Slider usw. nicht so kompliziert. Oder spricht was dagegen, was ich so nicht im Blick habe? Oder vielleicht habe ich auch einfach den Aufbau dieser beiden Seiten mit Menü nicht begriffen:
https://egw-kerzers.computech.dev/agenda
https://egw-kerzers.computech.dev/agenda/liste

**Comment by szeberli** [comment]
Wer werden das prüfen.
