### ISSUE TITLE
Losungen werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#122]
Zurzeit wird der Losungenblock nicht angezeigt.

<img width="1280" alt="Bildschirmfoto 2021-10-18 um 14 28 59" src="https://user-images.githubusercontent.com/90800460/137730724-1fba7a6b-982e-4640-b7ac-fffafb29a0b9.png">

**Comment by szeberli** [comment]
Morgen wird es wieder gehen.
es schein ein Datenbank fehler von http://www.combib.de zu sein.
