### ISSUE TITLE
Publikation Export

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#13]
Für die Übermittlung der Publikation an die Zeitungsredaktion muss die Tabelle exportiert werden können.

**Comment by szeberli** [comment]
@bernhard-rohrer 
Markieren -> Excel -> einfügen. DONE

**Comment by bernhard-rohrer** [comment]
Typischerweise ist Excel nicht das Format, um Meldungen an eine Inserate-Redaktion zu machen. Wir müssen z.B. ein *.doc liefern.
