### ISSUE TITLE
Agenda Datenexport - ergänzung mit Namen

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#133]
Wäre es möglich, im ical noch weitere Daten zu integrieren? 
Unter DESCRIPTION wird der Verantwortliche mit Kürzel bereits integriert. 
Für uns wäre es nützlich, auch die Kürzel der zugewiesenen Personen zu haben: z.B. Botschaft, Moderation, Musik.

**Comment by wermelst** [comment]
Es geht immer noch ums Thema drucken - zumindest für ein Arbeitsdokument. Ich weiss, dass der Dienstplan ins Excel copy&pasted werden kann. Aber ich habe nun ein bisschen herumgespielt und versucht, dies zu automatisieren. 
Falls die Daten einfach zur Verfügung gestellt werden können (REST, json oder so), wäre das super.

**Comment by szeberli** [comment]
@wermelst 
wird beim nächsten Depoloy ausgerollt
![grafik](https://user-images.githubusercontent.com/10152825/157426142-fef6a421-2e09-4730-afa9-ff5a6d5ac251.png)

**Comment by gonzo008** [comment]
Wäre es möglich beim xls-Export die vollen Namen anzuzeigen und nicht nur die Abkürzungen?

**Comment by szeberli** [comment]
@gonzo008 
Dies ist grundsätzlich möglich- dies müsste ich jedoch stark um -> neu Bauen. dies würde ca 1h Arbeit benöltigen. 
darf ich eine Offerte machen?
