### ISSUE TITLE
Benutzersuche

### ISSUE THREAD

**Issue by staubthom** [szeberli/EGW-Webseite#135]
Bei der Suche nach Benutzer steht: "Name oder E-Mail-Adresse enthält:" Die Suche beschränkt sich aber auf Benutzername oder E-mail. Name oder Vorname werden nicht durchsucht. Das ist aber sehr wichtig, weil Email oder Benutzername manchmal nicht viel über eine Person aussagen.

**Comment by bernhard-rohrer** [comment]
@staubthom In der Kontaktliste im Intranet-Menu kannst du nach Vor- und Nachnamen suchen.
