### ISSUE TITLE
Passwort rücksetzen als Admin

### ISSUE THREAD

**Issue by staubthom** [szeberli/EGW-Webseite#136]
Wenn ich als Admin bei einem Benutzer das PW zurücksetze, erhält dieser aktuell kein "E-Mail mit dem Passwortzurücksetzen link. Ich hatte aber auch schon, dass so ein Email kam, jedoch hat der Link darin nicht funktioniert.  Bitte nochmals Testen.

**Comment by bernhard-rohrer** [comment]
Das hat bei mir jetzt schon mehrfach funktioniert.

**Comment by szeberli** [comment]
@staubthom, dies wird funktionierten wenn die Webseite online gestellt wurde... sonnst einfach nochmals melden ;).
