### ISSUE TITLE
Wochenansicht der Agenda

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#137]
Bei der Wochenansicht der Agenda braucht es einen Punkt nach dem ersten Tag, z.B. 6**.** – 12. Dez. 2021.
Die Zeit von 0 bis 7 Uhr scheint mir eher überflüssig zu sein, vielleicht könnte man diese komprimiert anzeigen, so dass die Wochentage-Beschriftung nicht zu schnell aus dem Scrollfenster verschwindet.
Die Spaltenlinien der Tage müsste man durchziehen und evtl. die Wochentage-Beschriftung unten noch mal wiederholen.

<img width="1280" alt="Bildschirmfoto 2021-10-29 um 18 34 34" src="https://user-images.githubusercontent.com/90800460/139471995-4a770a41-fb1a-4a7f-b153-5b6883adcd2f.png">

**Comment by szeberli** [comment]
@NiklausMosimann 
dies wird nicht so einfach umsetzbar sein.

**Comment by gonzo008** [comment]
Dies wäre wirklich wünschenswert, sonst ist die Wochendarstellung nicht wirklich brauchbar...

**Comment by szeberli** [comment]
@NiklausMosimann 
kommt beim nächsten Deploy
