### ISSUE TITLE
Benutzerrechte

### ISSUE THREAD

**Issue by ThiBiss** [szeberli/EGW-Webseite#139]
Ich habe mir einen Testbenutzer ohne Rechte angelegt.

Wenn ich mich mit diesem Benutzer anmelde kann ich trotzdem Agendaeinträge bearbeiten, Dienstpläne ändern etc., und habe Zugriff auf die Passwortgeschützte Seite. Nach meiner interpretation der Tabelle mit den Zugriffsrechten sollte dies nicht so sein.

Da wir im Sinn haben den Benutzern die entsprechenden Rechte zuzuweisen möchte ich Euch bitten, dies mal anzusehen. (oder mir zu sagen was ich falsch mache...)

**Comment by robinaustiin** [comment]
@ThiBiss  Ich habe die Berechtigungen nochmals überarbeitet. Wird beim nächsten Deploy angepasst.

**Comment by bernhard-rohrer** [comment]
Ich habe einen Benutzer ohne Rechte angelegt und der kann immer noch Agenda-Einträge bearbeiten.

**Comment by szeberli** [comment]
Wir haben dies korrigiert und angepasst.

**Comment by bernhard-rohrer** [comment]
Diesmal funktioniert es bei mir. Danke.
