### ISSUE TITLE
Publikation Felder

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#14]
Je nach Bedürfnis sollten die aufzulistenden Felder (Spalten) konfiguriert werden können.

**Comment by szeberli** [comment]
@bernhard-rohrer Welche Felder erwartest du heir?

**Comment by bernhard-rohrer** [comment]
Nun, je nach Bedürfnis des Bezirks wird das unterschiedlich sein. Ich denke man sollte die Felder definieren können. Manche publizieren z.B. den Redner oder ob es eine Kinderbetreuung gibt.
