### ISSUE TITLE
Bestätigung Bildrechte mit falschem Benutzer

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#140]
Bei jedem Bild, welches ich einfüge, erscheint eine Fehlermeldung betreffend Rechten, aber mit dem Benutzer niklaus.mosimann.
![grafik](https://user-images.githubusercontent.com/72626679/140194265-80b8b34e-5323-4dd1-8d06-65f4a5f16d6c.png)

**Comment by robinaustiin** [comment]
@bernhard-rohrer Ist dies der Fall, da in diesem Absatz bereits einmal ein Bild von niklaus.mosimann hochgeladen wurde?
Ich konnte den Fehler jedenfalls nicht nachbauen.

**Comment by szeberli** [comment]
@bernhard-rohrer 
ich habe das mit verschiedenen Situationen getestet. ich kann keinen fehler finden.

**Comment by szeberli** [comment]
@bernhard-rohrer 
Problem gefunden und behoben
![grafik](https://user-images.githubusercontent.com/10152825/153362916-1a56d341-fdf2-4c02-aa2a-a76080fb1d8e.png)
