### ISSUE TITLE
Duplizieren mit Dienstplanung

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#141]
Um die Jahresplanung inkl. dummy-User in den benötigten Diensten eintragen zu können, braucht es einen weiteren "Duplizieren inkl. Dienste"-Button.

**Comment by bernhard-rohrer** [comment]
Aktuell werden beim Duplizieren alle Einträge in der Dienstplanung des Originals in der Kopie gelöscht. Ich erstelle aber für die Planung z.B. einen Gottesdienst und fülle in alle Dienste, welche für diesen Anlass benötigt werde den Dummy-Benutzer "Wird Benötigt". Dann sehen die Dienstgruppen-Verantwortlichen, wo überall sie Mitarbeiter suchen müssen. Diesen Gottesdienst kopiere ich dann über das ganze Jahr. Dabei sollten die Einträge in der Dienstplanung erhalten bleiben.

**Comment by DanielJenezerEGWH** [comment]
Das ist eine gute Idee, sollte weiterverfolgt werden.

**Comment by bernhard-rohrer** [comment]
Die Idee ist nicht mal neu. Das war schon mal so und wurde dann geändert.

**Comment by szeberli** [comment]
![grafik](https://user-images.githubusercontent.com/10152825/140771245-a8a67d1c-4e09-4db8-8d19-63afc3935fc4.png)

**Comment by szeberli** [comment]
Kommt beim nächsten Deploy

**Comment by DanielJenezerEGWH** [comment]
Merci.

**Comment by bernhard-rohrer** [comment]
@szeberli gibt es einen Zeitplan für den nächsten Deploy?

**Comment by szeberli** [comment]
@bernhard-rohrer habe es soeben (nur für euch) ausgerollt

**Comment by bernhard-rohrer** [comment]
@szeberli Habe es schon gesehen, danke. Leider bekommt beim Duplizieren mit Dienstplanung der Titel wieder ein "- Cloned" angehängt. Bekommen wir das auch wieder weg?
Zudem wird beim Speichern die Belegung der Räume nicht überprüft.

**Comment by szeberli** [comment]
@bernhard-rohrer  Leider ist das nicht ganz so einfach... -- dachte ich mir schon , dass diese Frage kommen würde ;)

**Comment by bernhard-rohrer** [comment]
@szeberli 
Hatten wir denn die Funktion duplizieren mit Dienstplanung aber ohne Zusatz beim Titel nicht schon einmal?

**Comment by szeberli** [comment]
@bernhard-rohrer Ja da hatten wir schon mal -> ich habe ein weiteres Modul verwendet um die Seite mit Diensten zu Clonen aber bei diesem module ist das nicht angedacht.... (man kann leider nicht der Fünfer und den weggen bekommen ;S)
