### ISSUE TITLE
not published in Raumbelegung

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#142]
Anlässe, welche den "Published"-Schalter auf inaktiv haben, müssen trotzdem schon in der Raumplanung ersichtlich sein. Sonst werden diese bei externen Belegungen nicht beachtet.

**Comment by robinaustiin** [comment]
@szeberli ist es möglich unveröffentlichte Einträge darzustellen?

**Comment by szeberli** [comment]
@bernhard-rohrer 
Wenn inhalte auf "nicht veröffentlicht" gesetzt sind, sollten diese ja nicht in der Liste angezeigt werden.
da diese Inhalt nicht veröffentlicht ist. 
diese Inhalte können unter [Content] dann danach gefiltert werden:
![grafik](https://user-images.githubusercontent.com/10152825/140890190-e6c7ebe4-5b28-4e72-a577-b5b5fa387fd6.png)

**Comment by bernhard-rohrer** [comment]
@szeberli Betreffend der öffentlichen Agenda gebe ich dir natürlich Recht, aber betreffend der Raumbelegung stimme ich nicht zu. In der Raumbelegung (nicht öffentlich) sollten sie sichtbar sein. 
Beim Speichern eines neuen Agenda-Eintrags müssen die geplanten Termine (pubilshed nicht gesetzt) zwingend mit geprüft werden.
