### ISSUE TITLE
Stornierte Anlässe bleiben öffentlich sichtbar

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#143]
Wird ein Anlass auf storniert gesetzt, sollte dieser in der öffentlichen Agenda nicht mehr sichtbar sein.

**Comment by bernhard-rohrer** [comment]
Das hat bei mir jetzt auch funktioniert.

**Comment by bernhard-rohrer** [comment]
Das Problem ist wieder da!

**Comment by bernhard-rohrer** [comment]
In den Listen Publikation und Screen sind die stornierten Einträge noch sichtbar.

**Comment by szeberli** [comment]
@szeberli kommt beim nächsten Deploy
