### ISSUE TITLE
Darstellung Sonderzeichen in der Raumbelegung Kalender-Ansicht

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#144]
Sonderzeichen im Titel werden in der Kalender-Ansicht nicht richtig dargestellt.
![grafik](https://user-images.githubusercontent.com/72626679/140196243-abf0cd58-7ab5-4e5a-a5f4-aaad18f6c52a.png)
In der Listen-Ansicht ist die Darstellung korrekt.
![grafik](https://user-images.githubusercontent.com/72626679/140196328-3c497eaa-2cf3-4757-8304-cf7d9b69ce1b.png)

**Comment by bernhard-rohrer** [comment]
Das Problem mit den Sonderzeichen ist in der Raumbelegung und der iCal Schnittstelle immer noch da:
DESCRIPTION:Test mit &amp;quot;Ümlautén&amp;quot; &amp;amp; &amp;quot;Sönderzeichen&amp;quot;\n
![grafik](https://user-images.githubusercontent.com/72626679/149893239-c43fc7f6-4847-4189-a5dd-00855f63a990.png)

**Comment by szeberli** [comment]
/admin/structure/views/view/agenda_ical/edit/ical_2
