### ISSUE TITLE
Dienstplan

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#146]
Für mich ist unklar, warum die verschiedenen Dienste nicht von den einzelnen EGW's festgelegt werden können.

Zudem brauchen die nicht verwendeten Dienste unnötig Platz.

Aus meiner Sicht braucht es wie bei den Räumen eine Strucktur, die für die Gemeinde eine bearbeitbare Organisation ermöglicht, ähnlich wie bei den Räumen.

**Comment by szeberli** [comment]
Sobald der entwicklungs Moduls abgeschaltet ist und die Webseite online ist, werden nur die Deinete angezeigt, welche auch verwendet werden.
