### ISSUE TITLE
ausdrucken/exportieren

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#147]
Die Kalenderanwendeungen, wie Agenda, Dienstplan, Raumbelegung, müssen ausdruckbar sein oder zumindest in ein übliches Format wie z. B. Excel (oder Text mit ;) exportiert werden können.

**Comment by szeberli** [comment]
#133

**Comment by DanielJenezerEGWH** [comment]
Also, habe mich wieder an die Schulung erinnert: ...  Ich weiss, dass der Dienstplan ins Excel copy&pasted werden kann. ...
Nicht gerade benutzerfreundlich.

**Comment by suterma** [comment]
Um das Layout spezifisch für Ausdrucke zu verbessern, habe ich eine kleine CSS-Library geschrieben. Für das CSS-Framework Bulma zwar eigentlich, aber es besteht keine direkte Abhängigkeit und somit kann das überall verwendet werden:

https://github.com/suterma/bulma-print/blob/main/README.md#how-to-use

Damit könnte man z.B. ganz einfach Menus, Header und Footer ausblenden.
