### ISSUE TITLE
Suche fehlt

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#148]
Ein Suche fehlt.

**Comment by DanielJenezerEGWH** [comment]
Nicht alle Besucher der Seite finden in unserer Struktur, das was sie suchen.

**Comment by szeberli** [comment]
sind noch weitere Bezirke, welche eine eingebaute Suche wünschen? -> dies war bis jetzt kein Thema.

**Comment by bernhard-rohrer** [comment]
Mir persönlich hat das Feld noch nie gefehlt und ich wäre nicht auf die Idee gekommen. Aber so ein Suchfeld ist praktisch Standard, also warum auch nicht.

**Comment by szeberli** [comment]
wo müsste die Suche Platziert werden?
im Header -> https://www.besserfresser.ch/
oder im Footer?

**Comment by DanielJenezerEGWH** [comment]
Aus meiner Sicht ist im Header links üblich. Bei der laten war sie im Footer und musste "gesucht" werden.

**Comment by szeberli** [comment]
@DanielJenezerEGWH 
Die Suche kann nun eingebledet werden
