### ISSUE TITLE
Raumbelegung

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#149]
Die Raumbelegung stellt keine Überschneidungen/Konflikte fest:
![Doppelbelegung möglich](https://user-images.githubusercontent.com/93736658/140420443-97658fe2-d8d0-4dbe-8c54-ec0ec5455b3d.PNG)

**Comment by szeberli** [comment]
@DanielJenezerEGWH 
Ich kann den Fehler nicht reproduzieren.

Gerpüft wird nicht, wenn ein Inhalt Dupliziert wird.
