### ISSUE TITLE
Mehrere Personen pro Dienst

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#151]
Wir nutzen diese Dienste (noch) nicht, aber ich kenne Gemeinden, die für die folgenden Dienste mehrere Personen einteilen:
- Begrüssung
- Bistro
- ev. auch Saal Dienst
- Abendmahl (wenn das kommt)
Diese Felder sollten den gleichen Typ erhalten wie z.B. Gebet.

**Comment by szeberli** [comment]
@bernhard-rohrer 
werden wir dies umsetzen wenn es Autkell wird ;)
