### ISSUE TITLE
Unter-Menus Intranet

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#152]
Unter-Menus der Intranet Menu-Struktur werden nicht angezeigt (kein Pfeil nach unten, klappen nicht auf).

**Comment by bernhard-rohrer** [comment]
![image](https://user-images.githubusercontent.com/72626679/146991707-e332144c-648d-4dcf-802d-355b1ea6e729.png)
sieht auf der Homepage so aus:
![image](https://user-images.githubusercontent.com/72626679/146991785-0bb85eb3-3c95-4032-ada1-39095250cfc8.png)
Und auf einer Intranet-Seite dann so:
![image](https://user-images.githubusercontent.com/72626679/146991875-bad91e49-6956-46d7-9037-38b81ad99f5c.png)

**Comment by szeberli** [comment]
@bernhard-rohrer 
nun neu auch mit Level2 etc
