### ISSUE TITLE
Alias für gefilterte iCAL

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#157]
Sollen eine Gruppe von Anlässe (z.B. alle für Erwachsene oder alle Jugend-Anlässe) als iCAL abonniert werden, ist der Link komplex. Es wäre praktisch, für solche gefilterte iCAL einen Alias-Link anbieten zu können.

**Comment by szeberli** [comment]
@bernhard-rohrer 
Dies könnte zu Problemen führen, dass die Weiterleitung nicht korrekt wirkt. Vorallem wird es schwierig, da jeder Bezirk andere IDs hat
