### ISSUE TITLE
Duplizieren eines Agendaeintrags - Standort intern und extern wird gespeichert

### ISSUE THREAD

**Issue by siegm** [szeberli/EGW-Webseite#158]
Beim Duplizieren eines Agendaeintrags wird auch der Standort (extern oder intern) übernommen, was soweit korrekt ist. Wird jedoch anschliessend der Standort von intern zu extern oder umgekehrt gewechselt und versehentlich der ursprüngliche inkl. Attribute nicht manuell gelöscht, werden beide Optionen gespeichert.
Vorschlag zur Problemlösung: Beim Speichern wird nur die zu diesem Zeitpunkt gewählte Option inkl. Attribute beibehalten, die andere Option inkl. Attribute (bei intern allfällige Raumreservationen) wird automatisch gelöscht.

**Comment by szeberli** [comment]
@siegm es gab schon mal ein solches Issues

**Comment by bernhard-rohrer** [comment]
https://github.com/szeberli/EGW-Webseite/issues/121
