### ISSUE TITLE
Vergangene Agendaeinträge

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#161]
Bitte die vergangenen Agendaeinträge nicht ausblenden. Manchmal ist es hilfreich, wenn man noch schauen kann, was wann war, bzw. alte Einträge zum Duplizieren nbenutzen kann...

**Comment by szeberli** [comment]
@gonzo008 
Es gibt bereits eine solche Ansicht:
Z.B. https://egw.ch/intranet/dienstplan-history 
/intranet/dienstplan-history bei der URL ergänzen

Viel Erfolg ;)
