### ISSUE TITLE
Agenda Block x nächste Anlässe

### ISSUE THREAD

**Issue by ThiBiss** [szeberli/EGW-Webseite#162]
Für Agendablöcke in Tabellenform kann ich
"Nächster Anlass" oder "Alle Anlässe" auswählen.

Super wäre ein Zwischending, in dem ich zB. die nächsten drei, vier oder fünf Anlässe anzeigen kann.

**Comment by staubthom** [comment]
Für uns ist dieses Feature auch extrem wichtig

**Comment by szeberli** [comment]
@ThiBiss @staubthom 
Dies ist ein neues Feature,
Wir würden dies gerne machen Zeitaufwand ca 3-4h. Dürfen wir das offerieren?

**Comment by ThiBiss** [comment]
@szeberli
Ich war der Meinung, dass damit ev. auch gleich folgendes Problem behoben wäre:
Ich habe zur Auswahl: Alle Anlässe (Tabelle); Nächster Anlass (Tabelle) Nächster Anlass (Block)
Allerdings macht es keinen Unterschied ob ich "Alle Anlässe Tabelle" oder nur "Nächster Anlass (Tabelle)" auswähle, es werden immer alle Anlässe angezeigt. (soll ich dazu ein neues issue erstellen?)

Für 500-600.- sehe ich eher keinen Bedarf. Wurden schon andere Kostenpflichtige Features bestellt? Wie wurde es da gehandhabt? Momentan wäre es ja so, dass die "innovativeren" Gemeinden die Features bestellen, und alle anderen die dann auch verwenden können. Gibt es irgendeine Möglichkeit die Kosten im Nachhinein zu Teilen, wenn ein anderer Bezirk ein Feature auch verwendet?

**Comment by staubthom** [comment]
Wir haben uns mittlerweile an den grossen Agendablock auf der Frontseite gewöhnt. Sieht nicht sehr schön aus, aber ist praktisch. Uns ist das Feature aktuell zu teuer.

**Comment by szeberli** [comment]
erledigt
