### ISSUE TITLE
Agendaliste ist nicht aktuell

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#163]
Kann es sein, dass der Seitencache der Agendaseiten öfter aktualisiert werden sollte? Heute am 22. November sind immer noch die Einträge vom 21. November zuoberst und können auch mit Aktualisieren der Seite nicht weggebracht werden.

<img width="1280" alt="Bildschirmfoto 2021-11-22 um 21 32 07" src="https://user-images.githubusercontent.com/90800460/142931761-c8915a4e-9059-4069-bd85-7ab49b755b96.png">

**Comment by robinaustiin** [comment]
Es war so, dass Einträge vom Vortrag noch 2 Stunden angezeigt wurden - also bis 02:00.
Wurde korrigiert. Wird beim nächsten Deploy angepasst.

**Comment by NiklausMosimann** [comment]
Ok, danke. Heute, 25.11. um 11:39 Uhr sind auch immer noch die Anlässe vom 24.11. in der Liste. Gut, wenn das dann mit dem Deploy korrigiert ist.
