### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#164]
Neuerdings fehlen bei der Monatsansicht teilweise einzelne die Horizontallinien. Je nach Zoomstufe sind es andere,..
Bei der Wochenansicht sollten die Tage fixiert sein, damit man beim scrollen die Wochentage noch sieht. Und die vertikalen Linien zwischen den Tagen durchgezogen sein, damit man sieht, wo die Termine hingehören.
Bei der Monatsansicht brauchten wir wieder wie bei der alten Lösung die Möglichkeit die Monate direkt anzusteuern. Das Durchklicken der einzelnen Monate ist ziemlich mühsam.

**Comment by szeberli** [comment]
@gonzo008 Kannst du ein Bild im Kommentar einfügen?

**Comment by gonzo008** [comment]
Zoom 90%
![image](https://user-images.githubusercontent.com/93154612/143659534-9cb4e0a0-ecde-418d-90c4-698fb18d515d.png)

Zoom 100%
![image](https://user-images.githubusercontent.com/93154612/143659519-0de7cea6-9283-4481-b34c-eb715e9261b8.png)

Zoom 110%
![image](https://user-images.githubusercontent.com/93154612/143659572-59604fd9-b374-46cc-a0a9-aba53068b7fd.png)

**Comment by szeberli** [comment]
@gonzo008 
nach meiner Ansicht muss dies mit dem Display zu tun haben.
entweder Auflösung welche die Linien nicht richtig rednern kann. Eventuell in Kombination mit dem Kontrast.
