### ISSUE TITLE
Bilder doppelt nutzen

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#166]
Kann man auf ein bereits verwendetes Bild ein zweites Mal zugreifen (z.B. ein Bild das schon als Slider verwendet wurde ein zweites Mal in einen Slider verwenden ohne es erneut hochladen zu müssen)?

**Comment by szeberli** [comment]
Nein das ist nicht möglich.

Wir haben die Architektur bewusst so gebaut. Grund dafür ist; wenn ein Bild / Dokument hochgeladen wird und später gelöscht wird, dann wird es vom System aus dem Dateisystem ebenfalls entfernt. -> Datenbereinigung

Technisch Gesehen wäre dies möglich.
