### ISSUE TITLE
Anpassung [site:name]

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#167]
Wo sind [site:name] <[site:mail]>  definiert, bzw. können diese angepasst werden?  EGW belp würde ich gerne in EGW Belp anpassen.

**Comment by szeberli** [comment]
Diese sind bei den Globalen Einstellungen und können nur von uns anpassen -> was soll angepasst werden?

**Comment by gonzo008** [comment]
[site:name] gerne ein grosse B bei Belp => EGW Belp

**Comment by szeberli** [comment]
erledigt
