### ISSUE TITLE
Agenda Filter via URL bringt nur 1 Anlass

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#168]
Das im Dashboard beschriebene Vorgehen z.B. mit
https://www.egw-kerzers.ch/agenda/liste/55+29+13+54
bringt immer nur einen einzigen Anlass - auch wenn nur eine Anlassart gesetzt wird.

**Comment by szeberli** [comment]
erledigt

**Comment by NiklausMosimann** [comment]
Das Problem ist wieder da, es kommt nur ein Anlass.

**Comment by bernhard-rohrer** [comment]
Das Problem ist wieder aktuell.
