### ISSUE TITLE
Agenda mit Block aktualisiert nicht

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#171]
Beim Agenda mit Block, Auswahl nächster GD ist auch am Montag noch der GD vom Sonntag sichtbar. In der Agenda ist der GD nicht mehr ersichtlich. Erst nach Umtaxieren oder Löschen des vergangenen Sonntags, kommt der Neue zum Vorschein.
![image](https://user-images.githubusercontent.com/93154612/143824727-86f18330-c8e8-4287-ba90-17f043576002.png)
![image](https://user-images.githubusercontent.com/93154612/143824919-306b5de7-01d0-4c6e-8e23-9ce83cb2ce3c.png)

**Comment by robinaustiin** [comment]
Wurde korrigiert. Wird beim nächsten Deploy angepasst.

**Comment by gonzo008** [comment]
Wann ist das nächste Deploy zu erwarten? 
Und ab wann wird dann aktualisiert. Erst am nächsten Tag oder direkt nach Ablauf des End-Zeitpunkts?

**Comment by gonzo008** [comment]
Leider ist dieses Problem nicht behoben - im ausgeloggten Zustand kommt immer noch der GD von gestern (heute ist der 27.12.21), trotz cache löschen. Erst wenn ich mich einlogge, wird der vom 2. Januar angezeigt. Sobald ich mich wieder abmelde kommt wieder der Weihnachtsgottesdienst.

**Comment by gonzo008** [comment]
Hallo Simon

Leider ist das Problem nicht behoben ->
https://github.com/szeberli/EGW-Webseite/issues/171#issuecomment-1001670118

------
Tanja Wenger
EGW - Belp
Ressort Administration & Kommunikation


Am Fr., 17. Dez. 2021 um 17:32 Uhr schrieb Simon Zeberli <
***@***.***>:
