### ISSUE TITLE
Kalenderwoche in der Agenda

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#172]
Es wäre sehr hilfreich, wenn - wie in der alten Agenda - die Kalenderwoche sichtbar ist.

**Comment by robinaustiin** [comment]
Wird vom verwendeten Modul für den Kalender nicht unterstützt.

**Comment by gonzo008** [comment]
Eine ziemlich unbefriedigende Antwort. Dies ist eine Verschlechterung des IST-Zustands der alten Umgebung :-(

**Comment by szeberli** [comment]
@gonzo008 
Das Modul welche wir für den Einsatz von Agenda Unterstützt diese Fähigkeit nicht mehr. diese wurde nicht mehr eingerichtet. 
wenn dies doch gewünscht wird. 
dies müssten wir extra Programmieren. ich schätze einen Zeitaufwand von ca 4 -6h. 
Dürfen wir dir eine Offerte erstellen.

**Comment by szeberli** [comment]
![grafik](https://user-images.githubusercontent.com/10152825/148951952-ec48721e-fe2f-444c-a8c7-f0155c48a6ad.png)
