### ISSUE TITLE
Alte, leere Filtereinträge

### ISSUE THREAD

**Issue by ThiBiss** [szeberli/EGW-Webseite#178]
zB. unter Podcast kann man als Filter die Serie wählen.
Allerdings werden einem dort sämtliche "Serien" angezeigt die irgendwann mal vorhanden waren, aber nun gelöscht sind.
Beispielsweise sind auch noch die aufgelistet, welche wir in der Entwicklungsseite zu Testzwecken erstellt hatten,.

Die Suche nach etwas spezifischem wird stark erschwert, wenn viele Einträge in der Dropdownliste gar keine Ergebnisse zeigen.

Könnt Ihr diese "Toten Einträge" bitte automatisch abgleichen?

**Comment by szeberli** [comment]
gehe auf den Link:
/admin/structure/taxonomy/manage/podcast_thema/overview

dann bei Operations auf Löschen

![grafik](https://user-images.githubusercontent.com/10152825/152012083-196b78b3-aee3-4a1d-a924-9b00835ef2ab.png)
