### ISSUE TITLE
Löschen Taxonomie

### ISSUE THREAD

**Issue by gonzo008** [szeberli/EGW-Webseite#179]
Beim Löschen eines Anlasses unter Taxoomie verschwindet dieses wie gewünscht z.B. bei der Agenda Listen Auswahl.
Beim Dienstplan ist es aber immer noch da.

**Comment by szeberli** [comment]
Um Welcher Taxonomy Begriff handelt es sich?

**Comment by szeberli** [comment]
@gonzo008 
Kannst du mich Telefonisch Kontaktierne.
