### ISSUE TITLE
Agenda Blöcke - Anzahl Elemente definieren

### ISSUE THREAD

**Issue by szeberli** [szeberli/EGW-Webseite#182]
![grafik](https://user-images.githubusercontent.com/10152825/152491537-b69df061-9674-4110-a2ac-6e1b484874cb.png)

**Comment by bernhard-rohrer** [comment]
Dieser Parameter begrenzt aber auch alle anderen Agenda-Listen wie z.B. den Dienstplan oder die Raumbelegung.

**Comment by szeberli** [comment]
Bei der dev umgebung ist das nicht der Fall:
![grafik](https://user-images.githubusercontent.com/10152825/153360119-c17cca41-54c2-4912-97cf-34c2b06f9be9.png)
![grafik](https://user-images.githubusercontent.com/10152825/153360178-cc5f9de9-04ac-4587-b6cb-5286316b446e.png)
![grafik](https://user-images.githubusercontent.com/10152825/153360194-db160d85-e7d0-4be3-8f4b-05387ee67a23.png)

**Comment by bernhard-rohrer** [comment]
Auf der egw-kerzers.ch werden alle Listen durch den Parameter "Anzahl Elemente des Blocks "Alle Anlässe" beeinflusst.
![grafik](https://user-images.githubusercontent.com/72626679/153703880-94e183fc-a2eb-434d-898a-fcdce1471858.png)
![grafik](https://user-images.githubusercontent.com/72626679/153703992-c8132657-f9b1-401c-8598-34ebb89e2d47.png)
So auch die Pulblikation und der Screen:
![grafik](https://user-images.githubusercontent.com/72626679/153703921-94956c80-c595-4311-840d-963808bde2d3.png)

![grafik](https://user-images.githubusercontent.com/72626679/153704011-75ec8d35-2d7e-40ee-90df-115fd3a1425d.png)
![grafik](https://user-images.githubusercontent.com/72626679/153704037-dc3e2967-c7af-4554-b108-26eff5c1bab7.png)
![grafik](https://user-images.githubusercontent.com/72626679/153704055-e3d392a3-5bdd-4ec9-bd2a-78f5cc58c386.png)

**Comment by szeberli** [comment]
ist gefixt. wird heute vormittag ausgerollt
