### ISSUE TITLE
Dienstplan Editor Warnung beim verlassen

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#185]
Der Dienstplan-Editor sollte beim verlassen der aktuellen Seite (Ansicht oben wechseln oder Seiten-Wechsel unten) noch einmal ans Speichern erinnern mit der Möglichkeit, den Wechsel abzubrechen und zuerst zu speichern.

**Comment by szeberli** [comment]
erledigt - rollout beim nächsten Deploy

**Comment by bernhard-rohrer** [comment]
Kannst du diese Warnung auch noch beim Ändern des Filters (Übernehmen Knopf)
![grafik](https://user-images.githubusercontent.com/72626679/153703699-1aca7f5c-40e7-4783-b565-b3006f0ef29b.png)
und beim Wechsel der Seite unten (vor, zurück, Seitenzahl)
![grafik](https://user-images.githubusercontent.com/72626679/153703733-26d9deb2-d826-414e-bb0a-0cf75825b5b0.png)
anzeigen? Das wäre dann perfekt.
und bei
