### ISSUE TITLE
Screen Liste ist leer

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#187]
Nur auf der Entwicklungsumgebung ist die "Screen" Liste immer leer. 
![grafik](https://user-images.githubusercontent.com/72626679/153704342-0e0950ed-4603-45bf-b8b4-1cc35298754d.png)

**Comment by szeberli** [comment]
Diese Liste -> sind bei den näcshten 14 Tagen.... 

![grafik](https://user-images.githubusercontent.com/10152825/153705879-8a6df6a9-e63c-4c94-bbc5-2dd42ac197eb.png)
