### ISSUE TITLE
Slider Bilder nicht mehr konfigurierbar

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#191]
Im Slider konnte man jeweils das Verhältnis des Bildes auswählen, ebenso den Ausschnitt, den man zeigen möchte. Doch diese Funktionen sind nicht mehr auffindbar.

Man kann einfach die Foto hochladen und fertig… und es sieht dann nicht mehr so gut aus.

**Comment by szeberli** [comment]
@wermelst Hallo
Vielen Dank fürs melden des Fehlers.
Ich habe es soeben gefixt

**Comment by wermelst** [comment]
Hallo @szeberli 
Aktuell kann ich zwar wieder Fotos hochladen und den Ausschnitt auswählen, jedoch kann ich diesen Vorgang nicht abschliessen / speichern:
`Fehler wurde gefunden: xx (user) gave consent on 09.02.2021 - 18:45`

**Comment by szeberli** [comment]
@wermelst 

![image](https://user-images.githubusercontent.com/10152825/158429946-6a9a39c5-2b1c-4200-899b-2ef8cd368168.png)

Noch bestätigen dass du die bildrechte hast.

**Comment by wermelst** [comment]
Ja, geht jetzt. Einem vorhandenen Foto fehlte die Zustimmung.
