### ISSUE TITLE
Bildergalerien können nicht mehr erstellt werden

### ISSUE THREAD

**Issue by lindasteiner** [szeberli/EGW-Webseite#193]
Gerade wollte ich eine Bildergalerie für den Jugendleitertag+ 2022 erstellen, jedoch gelingt mir dies nicht mehr. Egal ob alle Fotos auf einmal oder nur ein einzelnes Foto: Ich erhalte jeweils Fehlermeldungen. Mache ich etwas falsch oder hat sich da ein bug eingeschlichen?
![Vor dem Speichern](https://user-images.githubusercontent.com/84574647/159020988-d1ccdee2-f3b5-49cd-86a1-eab6a40976b5.PNG)
![Nach dem Speichern](https://user-images.githubusercontent.com/84574647/159020991-d941b967-7073-4eb2-a20a-48b0c2cf096a.PNG)

**Comment by szeberli** [comment]
behoben
