### ISSUE TITLE
Slider erscheint nicht

### ISSUE THREAD

**Issue by lindasteiner** [szeberli/EGW-Webseite#194]
Der Slider auf der Seite https://www.egw.ch/jugend/mission-trip erscheint nicht. Bug?

**Comment by szeberli** [comment]
Eine Person hat die Slider Region gelöscht -> werde softort wieder einrichten.

**Comment by szeberli** [comment]
so, läuft wieder ;) -> Viel Erfolg!

**Comment by lindasteiner** [comment]
super, danke!
