### ISSUE TITLE
Benutzer hinzufügen! mit Feld Geburtstag!

### ISSUE THREAD

**Issue by magnum6102** [szeberli/EGW-Webseite#196]
Benutzername
Einige Sonderzeichen sind erlaubt, z. B. Leerzeichen, Punkt (.), Bindestrich (-), Apostroph ('), Unterstrich(_) und das @ Zeichen.
Passwort
Geben Sie das Passwort für das neue Konto in beide Felder ein.

Status
Gesperrt
Active

Zuweisbare Rollen
Audio Uploader
Webform Creator
Agenda creator
Intranet creator
Content creator
Verwalter
Der Benutzer erhält die kombinierten Berechtigungen aller hier ausgewählten Rollen sowie der folgenden: Angemeldeter Benutzer.

 Benutzer über neues Konto benachrichtigen
Vorname
Nachname
Adresse
Land
**Geburtstag**

Straße
Straße (2. Zeile)
Postleitzahl
 
Stadt
Tel
062 999 00 00

**Comment by szeberli** [comment]
@Soned-1966 
von welchem Bezirk bist du?

**Comment by szeberli** [comment]
@Soned-1966
soll es auch eine Geburtstags Liste geben? so dass man sieht wer als nächstes Geburtstag hat?

**Comment by magnum6102** [comment]
Warum nicht wenn es geht!

**Comment by magnum6102** [comment]
![image](https://user-images.githubusercontent.com/102534981/160441399-75aa0dc1-7eae-437a-815c-257c46d394d4.png)
