### ISSUE TITLE
Kein Hauptmenu in der Mobile-View auf egw-kerzers.ch

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#197]
Das Hauptmenü in der mobile-Ansicht funktioniert auf unserer Seite nicht mehr (öffnet sich nicht). Andere Bezirke sind nicht betroffen.

**Comment by szeberli** [comment]
Repariert

**Comment by bernhard-rohrer** [comment]
@szeberli Super Service, besten Dank.
