### ISSUE TITLE
Webform - Bestätigungsmails kommen nicht an

### ISSUE THREAD

**Issue by lindasteiner** [szeberli/EGW-Webseite#198]
Einige der Angemeldeten fürs Teeniepfingsttreffen erhalten keine Bestätigungsmail obschon ihre E-Mailadresse richtig ist. Das Formular ist aber richtig eingestellt. Wo könnte das Problem liegen? Mittlerweile haben wir von 134 Anmeldungen ca. 20 Meldungen bezüglich dieses Fehlers erhalten.

**Comment by szeberli** [comment]
es drüfen nur @egw.ch adressen verwendet werden
@egw-jugend.ch sind nicht durch uns verwaltet, daher können wir das auch nicht verifizieren.

**Comment by lindasteiner** [comment]
Wir haben die Mailadresse für die Bestätigungsmails nun auf egw.ch geändert aber dennoch die Rückmeldung erhalten, dass nicht alle Bestätigungsmails ankommen. Machen wir etwas falsch?

**Comment by bernhard-rohrer** [comment]
Wir haben gleiche Probleme z.B. bei @gmx.ch Adressen. Mit @egw-kerzers.ch Adressen scheint es aber bisher immer funktioniert zu haben.
