### ISSUE TITLE
Ungewohnte Meldung

### ISSUE THREAD

**Issue by lindasteiner** [szeberli/EGW-Webseite#199]
Als ich heute den Slider ändern wollte erschien eine ungewohnte Fehlermeldung (siehe Foto).
Ich kann den Slider wie gewohnt ändern, aber die Meldung erscheint mir komisch. Fehler?
![Unbenannt](https://user-images.githubusercontent.com/84574647/165748741-4006d24e-4646-429c-9de0-321fd25c4508.PNG)

**Comment by szeberli** [comment]
@lindasteiner 
dies hat damit zu tun, dass P.S Warscheindlich ein Dokument mit selben Nahmen bereits vohher veröffentlicht hat.
