### ISSUE TITLE
Dienstplan auch für die Vergangheit anzeigen

### ISSUE THREAD

**Issue by suterma** [szeberli/EGW-Webseite#201]
Der Dienstplan filter per Default und ohne Möglichkeit nur auf künftige Ereignisse.

Ich möchte aber beispielsweise den Dienstplan für das vergangene Wochnende einsehen, um z.B. Informationen bei der verantwortlichen Person von einem Dienst einzuholen.

Der Dienstplan sollte die Möglichkeit erhalten, den Zeitbereich auch in die Vergangenheit zu setzen.

**Comment by bernhard-rohrer** [comment]
Die Möglichkeit gibt es im Intranet-Menu unter Dienstplan History.
