### ISSUE TITLE
Hardcoded Registrierungscode? 

### ISSUE THREAD

**Issue by suterma** [szeberli/EGW-Webseite#202]
Im EGW Belp existiert der Hinweis auf einen speziellen Registrierungscode:

> Mit diesem Registrierungscode können Andere Perosnen ein Login anliegen
> 
> [REDACTED]

Das funktioniert tatsächlich genau so, mit dem Code auch im ausgeloggten Zustand. Damit kann ein beliebiger Angreifer die EGW-Seite als Mail-Schleuder verwenden, um z.B. ein beliebiges Mailpostfach zu füllen.

Ist dies nur ein Feature des EGW-Belp oder eine generelle Funktion? Ich schlage vor, dass es keine fixen Registrierungscodes gibt, sondern nur dynamisch erstellte, oder dass diese Funktion ganz entfernt. wird.

**Comment by szeberli** [comment]
hallo @suterma 
Der Registrierungs Code ist keine Sicherheitslüke. sondern das ist bewusst, So muss der Bezirk seine User nicht alle anlegen sondern kann es der Community übergeben. mit dem Zugangswort kann ein Benutzer ein Login erstellen. Kennt der Benutzer das Zugagnswort nicht, dann kann er kein Login erstellen.

Da ein Benutzer keine E-Mails aus dem System versenden kann. kann es auch nicht zu einer Mail-Schleuder kommen. 

Wir können gerne individuelle Codes generieren um dann einen benutzer zu erstellen. dies ist jedoch im Projektumfang nicht enthalten und müsste einzel verrechnet werden.

**Comment by suterma** [comment]
Hallo @szeberli 

Ja, das Zugangswort ist nicht öffentlich verfügbar, aber weil es offenbar beliegibt oft verwendet werden kann, finde ich es trotzdem ein Problem.

Das System versendet die "Willkommensnachricht", du solltest jetzt, zu diesem Zeitpunkt, einen Account beim EGW-Belp haben, mit ebendieser Willkommensnachricht, auf der Comput-Tech Firmenadresse. Das könnte verwendet werden, um eine Mailbox zu verstopfen. Du kannst den Account gerne sofort wieder löschen.

Die Generierung von Einmal-Codes sollte als Sicherheits-Feature zum Basis-Umfang gehören, nicht zu einem optionalen Paket. Sonst könnte man meinen, dass die Lösung in der Grundausstattung unsicher ist.

**Comment by szeberli** [comment]
Hallo @suterma 

Wenn benutzer sich selber Accounts erstellen sollten, dann ist das der einfachste Weg mit dem Registrierungscode. 
Natürlich ist es möglich, One Time Passwort zu erstellen, damit die Benutzer einemalig diesen verwenden können und sich ein neuen Benutzer anlegen können.  Das ist mit mehr arbeit verbunden für die verwalter der Webseiten. 

Als Alternative wäre es möglich dass nur der Verwalter die Benutzer hinzufügen kann. so würde eine Registrierung nicht möglich sein.

Was man natürlich auch mache könnte, ist 2FA -> aber das ist für viele Benutzer noch komplizierter und würden mit der Technik mühe haben. Jedoch der Sicherheits Aspekt wäre top :).

Gerne können wir das am nächsten Webmaster Treffen thematisieren.

**Comment by szeberli** [comment]
Hi @suterma 
ist ausgerollt
