### ISSUE TITLE
PDFs erzeugen 404 Seite

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#206]
Die angefügten PDFs können nicht heruntergladen werden und erzeugen eine 404 Seite. Zum Beispiel hier: https://egwspiez.ch/egw/zaeme-ab-55 

Spannenderweise funktioniert es bei mir an meinem Büro-Computer, aber bei andern nicht.

Wo könnte da das Problem sein?

**Comment by szeberli** [comment]
Hallo @thoesch 

ich kann das Problem nicht nachvollziehen.
Mögliche Tipps:

Dateinamen wie folg anpassen bevor diese hochgeladen werden:

- alles kleinbuchstaben
- keine Sonderzeichen
- keine Umlaute
- keine leerzeichen -> evtl. ersetzen durch  ein _ "Underline"

Falsch:
- Das ist unser Testdokument für die Webseite.pdf
Richtig:
- das_ist_unser_testdokument_fuer_die_webseite.pdf

Wie siet die Umgebung der betroffenen Personen aus?
- mit welchem Browser ist das problem
- welches Betribssystem

**Comment by szeberli** [comment]
Hallo @bernhard-rohrer

Haber ich das richtig verstanden, dass du das Problem auch festgestellt hast? Aber seither nicht mehr aufgefallen ist. -> somit könnte es einen Browser Bug sein?

**Comment by thoesch** [comment]
Ich denke das hat sich erledigt. Bei mir funkioniert alles (und auch bei der Person, die mir den Fehler gemeldet hat). Auch mit Dateinamen, die noch Grossbuchstaben und Leerschläge beinhalten. Danke für die Rückmeldung.
