### ISSUE TITLE
fehlende Rechte für "Content Creator"

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#207]
Die Benutzer des Typs "Content Creator" können keine Seite vom Typ "Einfache Seite" mehr erstellen oder auf Seiten mit dem Status "nicht veröffentlicht" zugreifen.
![grafik](https://user-images.githubusercontent.com/72626679/196247890-2f7570ed-0f04-4c88-ab18-e0131571de0a.png)

**Comment by szeberli** [comment]
@bernhard-rohrer 
bereit zum Testen auf dem DEV Server

**Comment by bernhard-rohrer** [comment]
Ich sehe da leider keine Verbesserung:
![image](https://user-images.githubusercontent.com/72626679/198362853-477040c7-d8ca-44be-b297-c0532652691d.png)

**Comment by szeberli** [comment]
@bernhard-rohrer 

Versuche es auf dem Testsystem ich habe es noch nicht deployd

**Comment by bernhard-rohrer** [comment]
Der Screenshot kommt vom https://egw.computech.dev/user/bero-0?check_logged_in=1

**Comment by bernhard-rohrer** [comment]
Bei der Korrektur ist wohl ein Recht zu viel aktiviert worden. Jetzt sehen alle nicht eingeloggten Benutzer einen Knopf "Ansicht".
![image](https://user-images.githubusercontent.com/72626679/205866394-5826f764-7cdb-4980-9659-c2b0328eec5b.png)

**Comment by szeberli** [comment]
@bernhard-rohrer 
done
