### ISSUE TITLE
Alte Seiten werden automatisch auf "nicht veröffentlicht" gesetzt.

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#208]
Jede Nacht werden ein paar Einträge auf "nicht veröffentlicht" gesetzt. Ist das gewollt und falls ja, was ist die Logik?
![grafik](https://user-images.githubusercontent.com/72626679/196249216-019bb564-40d5-4f88-afd6-76facc76ec1e.png)

**Comment by szeberli** [comment]
Hallo @bernhard-rohrer

Ja das ist bewusst. Die vergangenen Agenda Einträge werden automatisch nach (ca) 1 Monat nach Ablauf des Events deaktiviert. Dies ist vor allem dass google diese nachher nicht indexieren kann und über Google auffindbar sind.

Es gab Personen, welche über die Suchmaschine auf alte Events kamen.

**Comment by bernhard-rohrer** [comment]
OK, macht Sinn. Danke fürs klären.
