### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#213]
Öffne ich den Podcast über das Lautsprecher Symbol funktioniert das audio.
Öffne ich ihn über den Text Link funktioniert das Audio nicht mehr.

**Comment by szeberli** [comment]
@meggimannn 
Fehler gefunden und bei allen Projekten behoben!
Hier iser der Lösungsansatz: https://www.drupal.org/project/drupal/issues/3050261
