### ISSUE TITLE
Erstellung von mehrere Termine gleichzeitig

### ISSUE THREAD

**Issue by szeberli** [szeberli/EGW-Webseite#216]
Wer von euch wünscht dieses Feature?

**Comment by thoesch** [comment]
Für uns hat (wie bereits besprochen) diese Feature Priorität. Wir haben 10 - 15 wöchentlich wiederholende Raumreservationen zum Erfassen.

**Comment by bernhard-rohrer** [comment]
Auch bei uns gibt es eine Reihe von sich wiederholenden Reservationen. Die frage ist, ob das eine Serienreservation (ein Eintrag mit mehreren Daten) oder eine Serie von Reservationen (einzelne unabhängige Einträge) erzeugt. Ich würde die zweite Variante bevorzugen, da sich so z.B. Schulferien aus der Serie wieder entfernen lassen würden.

**Comment by thoesch** [comment]
> Für uns hat (wie bereits besprochen) diese Feature Priorität. Wir haben 10 - 15 wöchentlich wiederholende Raumreservationen zum Erfassen.

Wir sind auch bereit, diese Erweiterung zu bezahlen. Kannst du uns (EGW Spiez) eine Offerte senden, was das kostet?

**Comment by szeberli** [comment]
Danke @thoesch - Nun ist das nötige Budget zusammengekommen, damit wir mit der Entwicklung beginnen können.

**Comment by szeberli** [comment]
@bernhard-rohrer @thoesch 
Hallo Zusammen,
wir werden es demnechst deployen

![grafik](https://github.com/szeberli/EGW-Webseite/assets/10152825/54f76336-b39f-4434-af7d-a43e2e72b731)
