### ISSUE TITLE
Dienstplan: Duplizieren funktioniert nicht mehr

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#217]
Wenn ich im Dienstplan versuche, einen Termin zu duplizieren (Duplizieren - ohne D.), schlägt dies neuerdings Fehl: 
```
Oops!
404 - Page not found
Die Seite, die Sie suchen, wurde möglicherweise entfernt, ihr Name wurde geändert oder sie ist vorübergehend nicht verfügbar.
```

**Comment by bernhard-rohrer** [comment]
Hallo Stefan,
Ich habe Simon genötigt, die Funktion "Duplizieren - ohne D." zu entfernen, da diese immer wieder zu Doppelbelegungen geführt hat.
@szeberli: im Dienstplan ganz links auf dem Schreiber gibt es noch den Link auf die Funktion. Die müsste da noch weg.

**Comment by thoesch** [comment]
Für uns ist das eine ganz schlechte Lösung! So wird es statt einfacher noch schwieriger wöchentliche Raumreservationen zu erfassen.

**Comment by bernhard-rohrer** [comment]
Ich bin mir dem bewusst, ich habe selber genügend sich wiederholende Reservationen fürs nächste Jahr erfasst. Ich habe diese alle über "Duplizieren mit Diensten" erstellt. Dies ist aktuell die einzige Variante, die Doppelbelegungen zuverlässig verhindert.
Leider kann Simon beim "Duplizieren mit Diensten" den neu erzeugten Eintrag nicht gleich im "Bearbeiten" öffnen. Das führt halt zu diesem einen Schritt mehr.
Simon arbeitet aber bereits an einer Lösung für Termin-Serien ohne Dienste https://github.com/szeberli/EGW-Webseite/issues/218

**Comment by szeberli** [comment]
wird hier weiterverfolgt #216
