### ISSUE TITLE
Vorgang zum Duplizieren ist sehr aufwändig

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#221]
![grafik](https://user-images.githubusercontent.com/93736658/213670624-bc24e16f-f1c1-41b0-8f84-f7f8bdc3ec90.png)

**Comment by szeberli** [comment]
ist ein Duplikat von #217 und wird daher geschlossen

**Comment by DanielJenezerEGWH** [comment]
Sälü Simon

 

Für mich ist es nicht verständlich, dass man beim Duplizieren mit D. nicht direkt auf bearbeiten kann. Es wäre doch nur ein «nicht Anzeigen» von den Zwischenschritten.

 

Gruss Daniel

 

Von: Simon Zeberli ***@***.***> 
Gesendet: Mittwoch, 25. Januar 2023 14:00
An: szeberli/EGW-Webseite ***@***.***>
Cc: Daniel Jenzer ***@***.***>; Author ***@***.***>
Betreff: Re: [szeberli/EGW-Webseite] Vorgang zum Duplizieren ist sehr aufwändig (Issue #221)

 

ist ein Duplikat von #217 <https://github.com/szeberli/EGW-Webseite/issues/217>  und wird daher geschlossen
