### ISSUE TITLE
Essen: Die Auswahl ist nicht zweckmässig

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#222]
Man möchte u. U. sagen was es gibt: z. B. Brunch oder Sandwiches. Im übrigen beides nichtgerade gekocht. Folgende Punkte müssten möglich sein: Was wird angeboten [TEXT), wann wird es angeboten [vor dem Anlass inkl. Zeit; nach dem Anlass, Kosten, Liste zum Mitbringen beachten)
-> Offerte für die Änderungan D. Jenzer EGW Herzogenbuchsee.

**Comment by szeberli** [comment]
Haben wir soeben Deployt.
- Bestehende Daten sind migriert
- altes Feld- Essen deaktiviert.
