### ISSUE TITLE
Webseite ist langsam im neu laden

### ISSUE THREAD

**Issue by annakalt** [szeberli/EGW-Webseite#228]
Ich dachte es liegt an meinem schlechten WLAN, dass die Webseite langsam lädt. Aber da ich jetzt schon an verschiedenen Arbeitsplätzen Mühe hatte mit neu laden, denke ich es liegt eher an der Leistung des gesamten Systems der Webseite. Kann man das einmal anschauen?

**Comment by szeberli** [comment]
@annakalt 

Kannst du nochmals testen? 
Ich habe einen möglichen fehler gefunden
