### ISSUE TITLE
Tooltip Raumbelegung (Wochenansicht)

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#23]
In der Raumbelegung (Wochenansicht) werden nur die Belegungen als Balken und darin die gebuchten Räume dargestellt. Es fehlt die Angabe des Titel/Anlass. Diese Angabe könnte auch als Tooltip dargestellt werden.

**Comment by bernhard-rohrer** [comment]
Hallo Robin,
Ein Tooltip wäre sehr hilfreich. Wenn der Anlass nur kurz dauert oder mehrere Räume belegt, ist der Anlasstitel doch nicht sichtbar.

**Comment by bernhard-rohrer** [comment]
Hallo Robin,
Komischerweise funktioniert der Tooltip nur für Einträge, bei welchen der gesamte Text in der Anzeige Platz hatte (also genau für die Einträge, welche keinen bräuchten).
![Mit_Tooltip](https://user-images.githubusercontent.com/72626679/106507611-98d27480-64cb-11eb-990c-3a74e0e1c071.jpg)
![Fehlender_Tooltip](https://user-images.githubusercontent.com/72626679/106507632-9d972880-64cb-11eb-92db-10b84bcc3baa.jpg)

**Comment by szeberli** [comment]
@bernhard-rohrer 
Das Modul lässt dies leider nicht standart mässig zu. ich müsste das Programmieren...... daher würde ich das gerne weglassen
darf ich das Ticket schliessen?

**Comment by bernhard-rohrer** [comment]
Witzig ist ja, dass es für grosse Felder schon funktioniert, wo der Tooltip eigentlich gar kein Mehrwert bietet. Das ganz ist aber sicher ein Komfort-Feature und wir können auch ohne das gut arbeiten.

**Comment by szeberli** [comment]
@bernhard-rohrer Welchen Browser verwedest du? ich habe gar keine Tooltips
