### ISSUE TITLE
Dublizierte Einträge sind nicht publiziert

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#231]
Wird ein Agenda-Eintrag mir "Dublizieren mit D." , ist der neu erzeugte Eintrag nicht "publiziert". Das Flag "Saved cloned content as published" muss default auf true gesetzt sein.
Auch das Flag "Take ownership" sollte nach meiner Meinung auf true stehen. Dann ist auch ersichtlich, wer diesen Eintrag erzeugt hat.
![grafik](https://user-images.githubusercontent.com/72626679/228320498-ef17452a-be72-4e61-9096-ac0d119455fb.png)

**Comment by szeberli** [comment]
@bernhard-rohrer 
wird beim nächsten Deploy veröffentlicht

**Comment by szeberli** [comment]
![grafik](https://github.com/szeberli/EGW-Webseite/assets/10152825/7083d98e-6afe-48cb-9091-5ef9cfc83c51)
