### ISSUE TITLE
Hintergrundfarbe in Raumreservation / Agenda / öffentlich zu dunkel

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#233]
Damit Gemeindeglieder und potenzielle Mieter nachschauen können, ob ein Raum frei ist, haben wir die öffentliche Version der Raumbelegung auf unserer Homapage integriert: https://www.egwspiez.ch/intranet/raumreservation/kalender 

Für eingeloggte User erscheint die agendaansicht der Raumreservation gut leserlicht mit hellgrünnem Hintergrund und schwarzer Schrift. Wenn ich aber das Dokument als nicht eingeloggter User öffne, dann ist der Hintergrund Dunkelblau und nicht mehr wirklich leserlich mit der schwarzen Schriftt.

![grafik](https://github.com/szeberli/EGW-Webseite/assets/80530093/556f5798-e12b-4856-a96e-e3d5cfe9c926)

**Comment by szeberli** [comment]
@thoesch 
Danke für den Hinweis, ich habe den Fehler korrigiert.
