### ISSUE TITLE
Wenn Agenda Block auf 5 Elemente gesetzt ist, überspringt vorwärts Agendaeinträge

### ISSUE THREAD

**Issue by NiklausMosimann** [szeberli/EGW-Webseite#234]
Wenn ich im Agenda-Block (wenn nur 5 Elemente angezeigt werden) auf den Pfeil vorwärts klicke, dann werden Termine übersprungen und ich sehe sie erst beim Rückwärtsspringen.

<img width="1280" alt="Bildschirmfoto 2023-05-25 um 23 52 36" src="https://github.com/szeberli/EGW-Webseite/assets/90800460/abb3be6b-61a4-4db1-a74d-21306d9b800f">
<img width="1280" alt="Bildschirmfoto 2023-05-25 um 23 52 46" src="https://github.com/szeberli/EGW-Webseite/assets/90800460/d8ae652a-a5f7-4284-a1e1-5562000140ee">
<img width="1280" alt="Bildschirmfoto 2023-05-25 um 23 53 11" src="https://github.com/szeberli/EGW-Webseite/assets/90800460/57240d9a-2917-479d-85d2-52a7b2001f33">

**Comment by szeberli** [comment]
@NiklausMosimann 
wird beim nächsten Deploy ausgerollt -> Heute / Morgen
