### ISSUE TITLE
Duplizieren

### ISSUE THREAD

**Issue by DanielJenezerEGWH** [szeberli/EGW-Webseite#239]
Je nach Rechten, wird das "Zwischenfenster" Duplizieren nicht gleich angezeigt (mit viel englischem Text (Angenda creator) oder nur die Auswahlfelder (Verwalter). -> gleiche Darstellung.

Im Dienstplan erschein beim Stift noch immer "Dienstplan - mit D".

**Comment by szeberli** [comment]
@DanielJenezerEGWH 
- Übersetzung wurde hinzugefügt
- Im Dienstplan erschein beim Stift noch immer "Dienstplan - mit D". -> Das bleibt so.
ist korrigiert und wird beim nächsten Deploy
