### ISSUE TITLE
screen

### ISSUE THREAD

**Issue by renateaebersold** [szeberli/EGW-Webseite#240]
Startdatum > vorher: Formatierung mit einem Datum, Beispiel: Di. 17.10.2023
Startdatum > neu: Formatierung mit Start- und Enddatum, Beispiel: Di. 17.10.2023 - Di. 17.10.2023
Das führt zu einem Zeilenumbruch, was das lesen erschwert. Ein screenshot davon zu machen, ist fast unmöglich. Kann die Ansicht wieder geändert werden?

Foto vorher: <img width="257" alt="Bildschirmfoto 2023-10-17 um 21 51 27" src="https://github.com/szeberli/EGW-Webseite/assets/148279092/3616229b-5a59-4de8-9501-2c517629f6d5">
Foto nachher: <img width="238" alt="Bildschirmfoto 2023-10-17 um 21 52 29" src="https://github.com/szeberli/EGW-Webseite/assets/148279092/713cdb23-068f-414d-84d6-8860fcb2b5fc">

**Comment by thoesch** [comment]
Das würde uns auch sehr dienen, wir benutezn diese Daten für die Anzeige der nächsten Anlässe. Für uns wäre es noch besser, wenn nur die Startzeit stehen würde.

**Comment by szeberli** [comment]
@thoesch @renateaebersold 
diesen Fehler wurde bereits behoben.

![grafik](https://github.com/szeberli/EGW-Webseite/assets/10152825/6ee8faeb-03ac-49d2-a0c5-f25074842514)

**Comment by thoesch** [comment]
Auf der Übersicht Publikation / Zeitung ist der "Fehler noch". Und muss die Schlusszeit auch stehen, ich lösche die jeweils in allen Publikationen raus.

![grafik](https://github.com/szeberli/EGW-Webseite/assets/80530093/a707e8cf-33e5-45e6-b5ad-ef1568cb4023)
