### ISSUE TITLE
Feld im Agenda-Dialog umbenennen

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#241]
Keine grosse Sache, aber falls ohne grossen Aufwand möglich, sollte das Feld "Intern/Auswärts" umbenannt werden. Die Auswahl ist Im Haus" oder "Auswärts" und der Begriff "Intern" wird bei der Kalender Sichtbarkeit anders verwendet.
![grafik](https://github.com/szeberli/EGW-Webseite/assets/72626679/b5831ddf-4bff-4e2c-9ed1-1098fb356925)

**Comment by szeberli** [comment]
@bernhard-rohrer 
wird beim näcshten Deploy ausgerollt
