### ISSUE TITLE
Unteschiedliche Slider für Handy und PC

### ISSUE THREAD

**Issue by lindasteineregw** [szeberli/EGW-Webseite#242]
Aktuell muss alles auf dem Slider mittig ausgerichtet sein, damit es auf dem Handy nicht abgeschnitten wird. Besser wäre, wenn zwei Versionen hochgeladen werden könnten.

**Comment by lindasteineregw** [comment]
Hoi Simon
Wir bräuchten nur den Slider Gross. Gerne kannst du uns mal eine Offerte schreiben.

**Comment by szeberli** [comment]
@lindasteineregw 
brauchst du das schnell oder reicht ende Januar?

**Comment by lindasteineregw** [comment]
@szeberli 
Ende Januar reicht.

**Comment by szeberli** [comment]
![grafik](https://github.com/szeberli/EGW-Webseite/assets/10152825/07d2d9c0-6277-4414-bee3-21b3d0cf3152)
übersicht
![grafik](https://github.com/szeberli/EGW-Webseite/assets/10152825/216d19f7-6b33-4869-adf3-74f7d6d824ae)
