### ISSUE TITLE
Handyslider Format ändern

### ISSUE THREAD

**Issue by lindasteineregw** [szeberli/EGW-Webseite#244]
Das Format des Handysliders ist mit 2048x2048 sehr ungünstig, da es auf dem Handybildschirm zu viel Platz einnimmt. Wäre es möglich diese Format auf 16:9 zu ändern (oder noch dünner)?
#242 @szeberli

**Comment by szeberli** [comment]
@lindasteineregw 
beim nächsten Deploy sind die Dimesonen FullHD (1920x1080)
