### ISSUE TITLE
Link bei Boxen ohne Button

### ISSUE THREAD

**Issue by lindasteineregw** [szeberli/EGW-Webseite#246]
Wir wären froh drum, wenn bei Boxen der Link auch ohne einen Button eingebunden werden könnte. Ein Klick aufs Bild (oder sogar die ganze Box) müsste reichen.

**Comment by szeberli** [comment]
Ich hatte das mal so gemacht, (da es im Design schöner aussieht) Doch die Personen sehen dann nicht, dass es hier einen Link hat. 
dies ist verwirrlich.  -> UX

Können wir dsa so belassen?

**Comment by lindasteineregw** [comment]
Ich konnte nun den Button deaktivieren (frag mich nicht wie, es hat im CSS bereits den richtigen Text drin gehabt. Ich wüsste also gar nicht, wie ich ihn nun wieder aktivieren könnte...)

Nun wäre meine Frage, ob es die Möglichkeit gibt, die ganze Box mit dem Link zu versehen und nicht nur das Bild. Es ist meines Erachtens intuitiv, dass man auch ohne Button aufs Bild klicken kann (habe es mit einigen aus dem Büro getestet). Aber eine Verlinkung der ganzen Box wäre trotzdem gut, da nicht immer ein Bild hinterlegt wird. 

Zur Veranschaulichung: www.egw.ch/jugend/news.

**Comment by szeberli** [comment]
ha habe ich gemacht.... Melde dich bei mir (Telefonisch) damit wir das nötige besprechen können ;)
