### ISSUE TITLE
Darstellungsprobleme

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#249]
Bei der Darstellung sind mir zwei unschöne Darstellungsfehler aufgefallen, die seit ein paar Tagen auftreten.
Sowohl im Firefox, im Edge und auch Mobile.

1. Bei den Blog-Artikeln erscheinen die Vorschaubilder zu klein
![grafik](https://github.com/user-attachments/assets/387774e7-9a9e-4a0c-879d-c680de5594ab)

2. Die Bilder in Artikel werden nicht mehr korrekt angezeigt. Das Bild sollte rechts erscheinen und auch der Abstand zum Text stimmt nicht mehr.
![grafik](https://github.com/user-attachments/assets/f4df42a9-0bbe-4575-9386-013ee1d14258)

Liebe Grüsse
Thomas

**Comment by szeberli** [comment]
1. 
![grafik](https://github.com/user-attachments/assets/17bf8dde-c159-41d7-a339-9a32a8b4e62c)
ändern auf 12/12

![grafik](https://github.com/user-attachments/assets/d1a0e977-39b5-453e-afb0-1e266d78c317)


Die anderen Fehler konnte ich Korrigieren
danke fürs melden!
