### ISSUE TITLE
Eingebettete YouTube Videos funktionieren nicht mehr

### ISSUE THREAD

**Issue by Puu-egwjugend** [szeberli/EGW-Webseite#253]
Eingebettete YouTube Videos (Absatz -> Video mit Text) werden ohne Text nicht mehr auf der Seite angezeigt.
Video erscheint nur wen Text eingefügt ist, jedoch passt sich die Grösse des Videos an die Text länge an was sehr ungünstig ist.

**Comment by szeberli** [comment]
@Puu-egwjugend 
Kannst du einen link senden?

**Comment by Puu-egwjugend** [comment]
betrifft alle seiten. auch bezirkseiten

beispiel hier:
https://www.egw.ch/jugend/incil

**Comment by szeberli** [comment]
@Puu-egwjugend ich kümmere mich sofort darum

**Comment by szeberli** [comment]
@Puu-egwjugend 
ist repariert.... Danke fürs melden!
