### ISSUE TITLE
Anlass fehlt in Agenda

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#256]
Mir ist aufgefallen, dass in der Agenda (und auch in der Ansicht Screen) neu der Anlass nicht angezeigt wird und nur noch der Wert, der beim Erstellen des Termines bei "Titel/Thema" erfasst wurde. 

Das heisst, dass jetzt bei Anlässen bei denen bei Titel/Thema zusätliche Angaben gemacht werden, nicht mehr erscheint was es für ein Anlass ist. Unten ist ein Beispiel. Am 2. Oktober sollte stehen "Bibelgespräch mit Thomas Oesch" oder auch bei den Gottesdiensten fehlt der Anlass "Gottesdienst" Kann das wieder rückgängig gemacht werden? Sonst müssen wir alle Anlässe mit ergänzenden Angaben anpassen.
Liebe Grüsse 
Thomas
![grafik](https://github.com/user-attachments/assets/c162d7be-b73c-406f-a89f-9a59d4cf7ed7)

**Comment by szeberli** [comment]
Hallo Thomas
Dies habe ich auf wunsch speziell so angepasst. 
Für mich macht es so sinn. man kann oben nach dem Anlass filtern. so können Benutzer dies filtern

**Comment by szeberli** [comment]
@thoesch
Die Lösung sieht nun so aus:
https://github.com/szeberli/EGW-Webseite/issues/257

Dies wird nun ausgerollt
