### ISSUE TITLE
Agenda darstellung (mit Anlasstyp oder ohne Anlasstyp)

### ISSUE THREAD

**Issue by szeberli** [szeberli/EGW-Webseite#257]
Es gibt Bezirke, welche die Agenda mit Anlasstyp anzeigen möchten, und es gibt solche die es ohne Anlasstyp anzeigen möcheten.
![grafik](https://github.com/user-attachments/assets/239a98ff-dac7-4c95-b5ab-781665c50581)
![grafik](https://github.com/user-attachments/assets/07ac07b9-61f0-4e7b-bb91-ec5ffa9f4eb2)

**Comment by szeberli** [comment]
Als lösung wird eine Einstellungsseite erstellt bei dem Benutzer ihre bedürfnisse selber einstellen können.
der Link ist im Dashboard: siehe Bild:
![grafik](https://github.com/user-attachments/assets/dfebb105-178e-4f51-ace7-9e47f05c4397)

**Comment by thoesch** [comment]
Danke vielmals - das dient uns sehr. Im Moment kommt bei mir noch eine Fehlermeldung wenn ich auf den Button "EGW Settings" drücke "403 - Access denied" obschon ich eingelogt bin mit der Rolle "Verwalter"

**Comment by szeberli** [comment]
@thoesch dann ist der deploy noch nicht follständig abgeschlossen. versuche es einfach erneut.

**Comment by thoesch** [comment]
Ich kann jetzt zwar die Einstellung ändern - aber an der Agenda ändert sich bei uns nicht und die Titel erscheinen bei beiden Einstellungen nicht mehr. An was könnte das liegen?

**Comment by szeberli** [comment]
Hallo @thoesch 
Stimmt ich habe ein Module vergessen im Deploy aufzunehmen dadurch hat es nicht funktoniert. 
Merci für die Meldung da bin ich dir Sehr danbkar!

Der Inhalt /node/3720 konnte nicht gespeichert werden, da dieser zu lange war. das system ist für so lange TItel nicht ausgelegt.
Familiengottesdienst zum Bezirks- und Erntedankfest. "Die kleine Maus und das goldene Blatt" Predigt: Thomas Oesch | Lobpreis mit Band mit Kinderhüte und Schatzkiste
