### ISSUE TITLE
Darstellung Layout Spalten

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#259]
Bei unserer Startseite haben wir ein dreispaltiges Layout. Seit 2 Wochen ist die mitlere Spalte leicht nach unten versetzt. Leider finde ich nicht raus, woran das liegt. Kann das wieder angepasst werden?

![grafik](https://github.com/user-attachments/assets/3d289fbf-4bb4-4bf3-8a2a-1f2cdea690fc)

**Comment by szeberli** [comment]
Der schlüssel ist:
![grafik](https://github.com/user-attachments/assets/251bfbb4-14d5-4985-b9d0-6f4d76b7543c)

**Comment by szeberli** [comment]
@thoesch 

ich habe soeben auch noch das Design bei den Spalten (im Backend) überarbeitet, um Bessere übersicht zu haben.
![grafik](https://github.com/user-attachments/assets/35c0ca2a-c9a3-407a-bb59-b0f2d51fc5a7)
