### ISSUE TITLE
Dienstplan: Export in Excel sollte eingestellte Filter berücksichtigen

### ISSUE THREAD

**Issue by manuelpankop** [szeberli/EGW-Webseite#261]
Wird ein Dienstplan als Excel exportiert, wird immer der gesamte Dienstplan in das Excel geschrieben

Es wäre super, wenn die eingestellten Filter (z.B. nur Gottesdienste) auch für den Export berücksichtigt werden.

**Comment by szeberli** [comment]
Hallo @manuelpankop 

Ist zur Zeit nicht vorgesehen, da es in Excel einfach ist, einen Filter zu setzen.
Wie wichtig wäre diese funkton? in der Skala von 1 (unwichtig) - 10(sehr wichtig)?

**Comment by manuelpankop** [comment]
Wir haben uns die Filter- und Sortierfunktion in Excel angeschaut. Damit können wir leben. Das Ticket ist damit obsolet.
