### ISSUE TITLE
Emails/Behandlungsroutinen von Webformularen werden nicht mehr korrekt angezeigt

### ISSUE THREAD

**Issue by lindasteineregw** [szeberli/EGW-Webseite#268]
Wenn ich eine neue Behandlungsroutine hinzufügen möchte, erscheint eine fehlerhafte Anzeige (siehe Bild --> fixe Anzeige, scrollen nicht möglich). So kann nicht mehr die gewünschte Behandlungsroutine ausgewählt werden. Auch über die Suchfunktion geht das nicht, da die gesuchte Routine nicht richtig angezeigt wird.

![Unbenannt](https://github.com/user-attachments/assets/5b028320-ab56-4f32-8ce6-4f752ef00592)

**Comment by szeberli** [comment]
@lindasteineregw 
es scheint ein Client Fehler zu sein
drücke mal die Taasten [CTRL] + [F5] 
so wird der Brwoser Cache geleert.

**Comment by lindasteineregw** [comment]
Habe ich ausprobiert, ändert aber nichts...

**Comment by szeberli** [comment]
@lindasteineregw 
schliesse mal den Browser oder leere den Cache.  -> oder verwende Firefox
starte allenfalls den PC neu

**Comment by szeberli** [comment]
@lindasteineregw 
kannst du mir den Titel / Link angeben bei welchen es nicht funktioniert?

**Comment by lindasteineregw** [comment]
Auch über Firefox geht es nicht

https://www.egw.ch/admin/structure/webform/manage/anmeldung_mission_trip/handlers
