### ISSUE TITLE
Gefilterte Agenda

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#28]
Ist es möglich, eine gefilterte Agenda anzuzeigen? 

Beispielsweise haben wir eine Seite für Jungschar. Da möchten wir alle Jungschi-Termine gleich direkt anzeigen. Es könnte z.B. im Stil sein vom Block-Typ "Nächste Events" - einfach gefiltert auf einen bestimmten Event-Typen.

**Comment by bernhard-rohrer** [comment]
Wenn für den Filter mehrere Anlässe kombiniert werden können, könnte das die aktuelle Zuordnung zu den Kalender Bezirk/Jugend im EGW Kerzers ersetzen.

**Comment by szeberli** [comment]
@wermelst + @bernhard-rohrer  das ist in Planung...

**Comment by szeberli** [comment]
@robinaustiin 

- [ ] Agenda als Block Darstellen
- [ ] Kontxtfilter auf Anlass wählen
- [ ] Absatz typ Text mit Block (und Kontextfilter) einrichten

**Comment by szeberli** [comment]
@wermelst 
du kannst den Link wie folgt
https://egw.computech.dev/agenda/liste/20

/agenda/liste/TaxonomyID
