### ISSUE TITLE
Agenda: Enddatum automatisch aktualisieren

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#35]
Es wäre praktisch, wenn das Enddatum / Zeit automatisch aktualisiert wird, nachdem man das Startdatum eingegeben wurde (also die Startzeit in die Endzeit übernommen). 
Ansonsten muss man immer zwei mal das gleiche Datum und die fast gleiche Zeit (z.B. +1h) auswählen.
![event-datum](https://user-images.githubusercontent.com/76686256/104584858-7f27d500-5663-11eb-9357-1f4bf91fb300.png)

**Comment by szeberli** [comment]
das ist noch Pendent -> ich arbeite noch an einer Lösung :)

**Comment by bernhard-rohrer** [comment]
Lässt sich dieser Mechanismus noch auf die Endzeit erweitern?
