### ISSUE TITLE
Slider: Default-Fotos und Seitenspezifische Fotos

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#36]
Ich möchte die Bilder des Default-Slider austauschen.
Dazu hab ich versucht, einen benutzerdefinierten Block zu erstellen und in der Slider-Region darzustellen. Doch das ist nicht kompatibel wenn ich auf einer bestimmten Seite Seitenspezifischen Slider-Fotos verwenden möchte..
Kann man evt. irgendwo einfach die Default Slider-Fotos austauschen, so dass ich den benutzerdefinierten Slider-Block nicht mehr brauche?
![slider](https://user-images.githubusercontent.com/76686256/104730827-0431ed80-573b-11eb-8e23-d931a7760e6e.png)

**Comment by meggimannn** [comment]
Du kannst die Seite als ganzes bearbeiten.
Dann erscheint oberhalb dem Titel im Reiter "Slider"
Dort kannst du überall deine eigene Foto hinzufügen

**Comment by wermelinger** [comment]
@meggimannn Genau, ich kann bei jeder Seite Bilder für den Slider definieren. 
Ich habe mich gefragt, ob ich die Standard-Bilder (vom Template) durch eigene Bilder ersetzen könnte. So dass ich nur für die Seiten manuell Slider-Bilder angeben muss, wo sie vom Standard abweichen. 
Aber wenn das nicht vorgesehen ist, werde ich sie bei jeder Seite einfügen.

**Comment by wermelst** [comment]
@meggimannn Genau, ich kann bei jeder Seite Bilder für den Slider definieren. 
Ich habe mich gefragt, ob ich die Standard-Bilder (vom Template) durch eigene Bilder ersetzen könnte. So dass ich nur für die Seiten manuell Slider-Bilder angeben muss, wo sie vom Standard abweichen. 
Aber wenn das nicht vorgesehen ist, werde ich sie bei jeder Seite einfügen.

**Comment by szeberli** [comment]
In Der Tat -> Das Standard Bild vom Slider ist im Design Definiert (bild) gerne kannst du mir dein Standard Slider zusenden, dann werde ich den dann einfügen.
