### ISSUE TITLE
Agenda Slider wechseln

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#37]
Wie kann ich bei der Agenda den Slider wechseln? da es Steffisburg geschafft hat, muss es möglich sein oder?

**Comment by wermelst** [comment]
Ich habe das gleiche Problem. Ebenso für die Seiten Blog und Podcast.

**Comment by szeberli** [comment]
Hier ist die Anwort:
https://github.com/szeberli/EGW-Webseite/wiki/Slider-in-Ansicht-(News,-Agenda,-Dienstplan,-etc.)
