### ISSUE TITLE
Block "Nächster Event"

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#38]
Der Block wurde am Webmaster Treffen gezeigt mit einem Bild enthalten.
Leider schaffen wird das nicht einen Termin so zu erstellen das in diesem Block dann der Anlass mit dem Foto erscheint.
ist das möglich?

**Comment by szeberli** [comment]
@meggimannn Du müsstes **Bild mit Text** verwenden.
Kannst du mir ein Anwendungszweck Angeben? -> bei eurer Bezirks Webseite?

**Comment by meggimannn** [comment]
Das immer der Aktuell nächste Anlass dort erscheint, und das nicht in einer Tabellen form, sondern eben mit Bild und text, danach Link zum Anlass.
Hast du das nicht am Webmastertreffen gezeigt? ich hatte das Gefühl das dort gesehen zu haben?

**Comment by szeberli** [comment]
@meggimannn nach meiner Ansicht war das Bild mit Text :)
So eine möglichkeit zu schaffen ist gut möglich zu machen, die Frage ist nur, was wollen wir zeigen, wenn der Nächsete Termin kein Bild zur verfügung hat.... hast du eine Idee?

**Comment by meggimannn** [comment]
@szeberli 
![Nächster Event](https://user-images.githubusercontent.com/77513711/105095746-5ad65900-5aa6-11eb-974d-f78940b77fef.jpg)
Irgend ein solch ähnliches Standbild..

**Comment by szeberli** [comment]
@meggimannn  so ist es im EGW Kleindietwil umgesetzt.... meinst du so -> einfach mit dem neuen Look?
![grafik](https://user-images.githubusercontent.com/10152825/105095961-b3a5f180-5aa6-11eb-99b2-36c64c4a6a56.png)

**Comment by meggimannn** [comment]
so ähnlich:
ich würde die Breite als ganze Seiten breite wie jeder Absatztyp machen.
![Nächster Event2](https://user-images.githubusercontent.com/77513711/105096907-0c29be80-5aa8-11eb-8169-67f2f5386c2e.jpg)
Habe mir jetzt nicht viel Zeitgenommen doch ungefähr so..

**Comment by szeberli** [comment]
@robinaustiin  kannst du im Screendesign einen vorschlag ausarbeiten?

**Comment by szeberli** [comment]
@robinaustiin 
bitte im Screedesign designen und mit @szeberli besprechen.
