### ISSUE TITLE
Agenda: Link "Anlass"

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#39]
In jedem Termin ist der "Anlass" ein Hyperlink, welcher auf komische Version des Termins verweist. Kann man den entfernen?

**Comment by szeberli** [comment]
das sind Revisionen (nur Super Admins sehen diese Revisionen)

**Comment by bernhard-rohrer** [comment]
Guten Morgen Simon,Du warst ja schon sehr fleissig.Der Link ist aber auch für nicht eingeloggte Benutzer vorhanden. Liebe Grüsse, Bernhard Am 19.01.2021 21:58 schrieb Simon Zeberli <notifications@github.com>:
das sind Revisionen (nur Super Admins sehen diese Revisionen)

**Comment by bernhard-rohrer** [comment]
Sowohl der Anlass als auch der Standort verfügen über einen Link, der zu keiner Seite mit weiteren Informationen führt. Diese sollten nicht erzeugt werden.
![Links_in_der Agenda](https://user-images.githubusercontent.com/72626679/106506809-8146bc00-64ca-11eb-9444-b9f0b3e0467d.jpg)

**Comment by szeberli** [comment]
@bernhard-rohrer 
Anlass Link ist entfernt
-> Standort ist korrigiert!
