### ISSUE TITLE
Slider Foto für Desktop und Mobile separat

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#44]
Die Anforderung an ein Foto ist enorm, wenn es 16/9 und 16/5 schön aussehen muss.
Deshalb würde ich es begrüssen das man Optional fürs Mobile ein separates Bild auswählen könnte.

**Comment by szeberli** [comment]
bei den Slider andere Fotos zu nehmen gibt sehr viel mehr Aufwand für die Benutzung.
Ich habe mir das auch überlegt, aber um es einfach zu halten weg gelassen. @meggimannn ist es o. k. für dich wenn wir das so lassen?￼

**Comment by szeberli** [comment]
@meggimannn wird geschlossen

**Comment by meggimannn** [comment]
Gäbe es nicht die Variante das Standart nur ein Foto reicht, wenn man auf einer Seite dann froh wäre könnte man einen Hacken Setzen (Für Mobile Seite anderes Bild wählen) danach kommt die zweite Maske zum Vorschein.
Ich denke das wäre ein Idealer Kompromiss für den einfachen und den Perfektionisten.
Nur ein Beispiel: https://egw-konolfingen.computech.dev/kafi-melody
Ab und an komme ich in die Versuchung im Banner einige Infos schon zu implementieren. mit nur einem Foto ist dies jedoch zu 99% nicht möglich.
Danke wenn du dir nochmals Gedanken darüber machst. ;-)
