### ISSUE TITLE
Button im Block immer gleiche Höhe

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#45]
Optisch wäre es schön wenn der Button im Block immer auf der Gleichen höhe ist. (sprich immer unten rechts und nicht dem Text zugeortnet.) https://egw-konolfingen.computech.dev (aus unserer Startseite ein Beispiel)

**Comment by szeberli** [comment]
@meggimannn danke für den Vorschlag

**Comment by meggimannn** [comment]
Wurde umgesetzt, danke
Nun sit ein Bug enthalten! Die Button's sind nur in der untersten Linie sichtbar.
