### ISSUE TITLE
Auf Mobile wird inhalt nicht angezeigt.

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#46]
Ich habe die Seite https://egw-konolfingen.computech.dev/unsere-grundsaetze erstellt.
Auf dem Desktop ist es okej, doch auf dem Mobile wird kein Inhalt angezeigt.

**Comment by robinaustiin** [comment]
Box-Elemente waren auf unveröffentlicht gestellt. Dadurch werden die Elemente nur im angemeldeten Bereich angezeigt.
![grafik](https://user-images.githubusercontent.com/60745729/106243712-1bc4a800-620a-11eb-9a43-15083d3885bc.png)
