### ISSUE TITLE
Agenda in Exel exportieren

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#48]
Kann man die Möglichkeit schaffen die Anlässe in ein Exel zu exportieren?
Oder die andere Variante ist, das es eine Jahresübersicht gerade auf der Webseite gibt.

Ich brauche die komplette Agenda eines Jahres auf ca. 1-5 A4 Blättern (Tabellarisch in die Monate gegliedert)

Ist eines davon Möglich?

**Comment by szeberli** [comment]
einfach die Tabelle markieren￼ dann kopieren.
Excel öffnen einfügen fertig￼

**Comment by szeberli** [comment]
@meggimannn  wird geschlossen
