### ISSUE TITLE
Agenda: Kann keine Einträge mehr erstellen / bearbeiten

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#50]
Ich wollte heute Agenda-Termine eintragen. Leider können überhaupt keine Events mehr gespeichert werden (weder neue noch bearbeitete). Es kommt immer der Fehler: `Auf der Website ist ein unvorhergesehener Fehler aufgetreten. Bitte versuchen Sie es später nochmal.`

**Comment by szeberli** [comment]
@wermelst ist korrigiert!

**Comment by wermelst** [comment]
Perfekt, danke!
