### ISSUE TITLE
Raumbelegung (Wochenansicht)

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#51]
Das erste Filterfeld Standort zeigt eine Liste aller Räume ohne Zusammenhang mit dem Standort und braucht es so nicht.

**Comment by szeberli** [comment]
@bernhard-rohrer kannst du mir die Links einfügen....

**Comment by szeberli** [comment]
Habe den Fehler gefunden ;)

**Comment by bernhard-rohrer** [comment]
Ich sehe den komischen Filter immer noch:
![Überflüssiger_Filter](https://user-images.githubusercontent.com/72626679/106505743-029d4f00-64c9-11eb-972a-9bd373577f10.jpg)

**Comment by szeberli** [comment]
@bernhard-rohrer 
Entfernt.
