### ISSUE TITLE
Raumbelegung: Information (intern/öffentlich)

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#53]
Ein Icon zur Unterscheidung von internen und öffentlichen Anlässen (z.B. in der hintersten Spalte) wäre cool.

**Comment by szeberli** [comment]
@robinaustiin im Selben zug die übersicht schöner gestalten...
![grafik](https://user-images.githubusercontent.com/10152825/108783737-4803e800-756e-11eb-89f2-72ce24768c04.png)
