### ISSUE TITLE
Agenda: Jahresplan Export

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#58]
Bei uns ist es ein Bedürfnis, die Agenda / Dienstplan irgendwie exportieren und auf Papier bringen zu können.
Ich bin mir bewusst, dass dieses Feature bewusst weggelassen wurde, um die Leute zu einem konsequenten Nutzen des Systems zu bringen. Allerdings ist die Realität, dass gewissen Leuten die Agenda auch in Papierform zugestellt werden muss. Es wäre praktisch, wenn das System eine solche Funktion bietet. Ansonsten machen wir es mit Copy&Paste und dann irgendwie aufbereiten.

**Comment by szeberli** [comment]
Du kannst in die Tablelle im Browser Markieren und Kopieren, dann ins Excel gehen ind einfügen. feritg
