### ISSUE TITLE
Nächster Anlass von der JG auf der JG Seite

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#59]
Es wäre noch eine tolle Funktion auf einer Angebotsspezifischen Seite (z.B.: JG) das man da der Block Nächster Anlass einsetzen könnte und dieser dann der nächste JG Anlass Zeigt. 
Da die Agenda schon sehr strukturiert und in Rubriken eingeteilt ist, gehe ich davon aus das dies möglich ist.?

**Comment by szeberli** [comment]
https://rz.computech.dev/egwstatus/
