### ISSUE TITLE
Agenda: Unterschiedliche Farben pro Anlass-Kategorie

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#60]
Wäre es möglich, die Agenda-Einträge unterschiedlich-farbig darzustellen? So, dass die unterschiedlichen Anlässe besser ins Auge stechen?

**Comment by szeberli** [comment]
das mit den Farben ist grundsätzlich möglihch, bringt jedoch diverse Probleme mit sich, vorallem beim Ausrollen bei in alle bezirkswebseiten.... daher würde ich das gerne nicht machen..
was meinst du, wenn wir das Ticket schliessen?

**Comment by wermelst** [comment]
Ok, alles klar.
