### ISSUE TITLE
Absatztype: Text mit Bild - Bildformat ändert sich mit Buttom

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#64]
Standart ist das Bild Hochformat.
Wenn mann jedoch einen Button unten dran platziert, fällt auf einmal der Bildzuschnitt raus und es wird das ganze Bild sichtbar. Sprich das Bild kann nicht mehr beschnitten werden. 
Beispiel Seite: https://egw-konolfingen.computech.dev/pfarrdienste

Ehrlich gesagt finde ich das so fast schöner, denn ein Hochformat Bild wird mit nicht viel Text extrem hoch.

**Comment by szeberli** [comment]
@meggimannn kannst du noch ein Bild einfügen? -> ein Screenshot hilft uns meistens

**Comment by szeberli** [comment]
@meggimannn 
wenn du Quehrformat Bilder verwenden möchtest, dann musst du Bild mit Text verwenden
Portrait sind Bilder Hochformat!
wird gefixt beim nächsten deploy
