### ISSUE TITLE
Agenda Monatsansicht: Zeitangaben werden falsch angezeigt

### ISSUE THREAD

**Issue by meggimannn** [szeberli/EGW-Webseite#65]
<img width="923" alt="Bildschirmfoto 2021-03-01 um 22 28 44" src="https://user-images.githubusercontent.com/77513711/109561573-a6d0e080-7add-11eb-9ca7-44442693c8a7.png">
Zeitangabe mit KK:00 statt der Richtigen Zeit

**Comment by szeberli** [comment]
ist gefixt, wird beim nächsten Deply angepasst.
