### ISSUE TITLE
Raumbelegung

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#7]
Die Raumbelegung zeigt zeitlich überlagernde Belegungen untereinander. Die Darstellung sollte als Kalender mit bei Überlagerung nebeneinander dargestellten Blöcken zeigen.

**Comment by bernhard-rohrer** [comment]
So wie in der Wochenansicht der Agenda.

**Comment by szeberli** [comment]
Das kann das Modul nicht welches wir eingesetzt haben..... oder es ist noch nicht so weit....

**Comment by bernhard-rohrer** [comment]
Du weisst für wie wichtig ich dieses Feature halte.
