### ISSUE TITLE
Anzeige "verwaiste Links"

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#71]
Es fehlt die Möglichkeit, verwaiste Links aufzulisten (analog linkchecker der alten Seite).

**Comment by szeberli** [comment]
Ist bis zum Jetzigen Zeitpunkt nicht möglich, da dieses Modul offiziell nicht gibt.
Dies müssten wir selber entwickeln.

**Comment by bernhard-rohrer** [comment]
Hallo zusammen,
Endlich hatte ich Zeit, mir das neue Feature anzuschauen. 
Es wäre hilfreich, wenn in der Liste mehr Details zur Seite mit den fehlerhaften Link gäbe. Besonders Links in einem Agenda-Eintrag in der Vergangenheit sollte als solche erkennbar sein, da meistens nicht mehr relevant.
Liebe Grüsse,  Bernhard

**Comment by szeberli** [comment]
@bernhard-rohrer 
lieder ist das nicht ganzt so einfach. ich müsste eein Contrib Module umbauen, -> aber dann bekomme ich keine zukünfige Updates mehr. desshalb wird es nicht angepasst.
