### ISSUE TITLE
Das Bezirkslogo fehlt noch

### ISSUE THREAD

**Issue by staubthom** [szeberli/EGW-Webseite#73]
Bei uns wird das Bezirkslogo nicht dargestellt. 
![logo](https://user-images.githubusercontent.com/80152194/110202536-9320d380-7e69-11eb-9634-9737db2767ad.png)

**Comment by robinaustiin** [comment]
Das Bezirkslogo kann als Block plaziert werden. Um welches EGW handelt es sich?

**Comment by staubthom** [comment]
EGW Unterlangenegg
Es sollte wieder so sein wie auf der aktuellen Seite.

[Ein Bild, das Text enthält.  Automatisch generierte Beschreibung]
Ich denke das geht nicht einfach als Block.
Ein lieber Gruss
Thomas


Von: robinaustiin ***@***.***>
Gesendet: Mittwoch, 31. März 2021 16:13
An: szeberli/EGW-Webseite ***@***.***>
Cc: Thomas Staub ***@***.***>; Author ***@***.***>
Betreff: Re: [szeberli/EGW-Webseite] Das Bezirkslogo fehlt noch (#73)


Das Bezirkslogo kann als Block plaziert werden. Um welches EGW handelt es sich?
