### ISSUE TITLE
Raumreservation in öffentlicher Seite einbinden

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#75]
Wie kürzlich telefonisch besprochen, möchten wir die Seite "Raumreservation", in der die Raumbelegung angezeigt wird auf unserer öffentlich zugänglichen Seite anzeigen können, so dass interessierte Mieter und die Putzteams ohne Anmeldung im Intranet sehen können, ob die Räume frei oder belegt sind. 

Ich sehe im Moment nicht, wie und ob das möglich ist?

Thomas Oesch
EGW Spiez

**Comment by szeberli** [comment]
@thoesch 
- eine Theoretisch ist das möglich, jedoch ist dsa Risiko gross, dass es mit Spams gefüllt wird.
- ich persönlich würde mit einem Webformular die nötigen infos abfagen und dann von hand übertrage.
-> was meinst du dazu?

**Comment by thoesch** [comment]
@szeberli 
Ich habe mich da wohl falsch ausgedrückt. Es ging nur darum, dass die Raumbelegung einsehbar ist. Was jetzt ja möglich ist. Von daher ist für mich dieser issue erledigt.

Danke.

**Comment by bernhard-rohrer** [comment]
Die Seiten /intranet/raumbelegung und /intranet/raumreservation sind ohne Login sichtbar. So kann ich alle internen Buchungen inklusive Titel sehen. 
- Ist das gewollt? Ich würde dringend eine reine Anzeige frei/besetzt empfehlen.
- Was ist der Unterschied der beiden Seiten?

**Comment by szeberli** [comment]
@bernhard-rohrer 
dies war die Anfoderung - Namen werden ja nicht angezeigt..

**Comment by bernhard-rohrer** [comment]
Nicht ganz, die Anforderung oben lautete: "sehen können, ob die Räume frei oder belegt sind" was ich als "digitale" Anzeige frei/belegt interpretiere. 
Ich habe ziemlich lange gebraucht, um das Verhalten der beiden Links  /intranet/raumbelegung und /intranet/raumreservation zu verstehen. Entsprechend lang wird die folgende Abhandlung ;-).
- Ich vermute, nur der Link /intranet/raumreservation (nur Anlass ist sichtbar) sollte öffentlich sein (kann man den noch aus dem "intranet"-Bereich verschieben?). Die Seite Raumreservation dahinter funktioniert grundsätzlich. 
Für den Zweck der reinen Belegungsanzeige bräuchte sie aber kein Filter auf Anlass und Sichtbarkeit mehr. Auch die Spalte "Sichtbarkeit" wäre nicht mehr nötig.
Der Kopf "History" muss weg.
- der Knopf "Woche" zeigt nach /intranet/raumbelegung/woche und damit zu den Einträgen inkl. sichtbarem Titel. Es fehlt eine Seite /raumreservation/woche mit unterdrücktem Titel.
- der Link /intranet/raumbelegung führt zu einer Seite, die auch Raumreservation heisst, aber die Anlässe inkl. Titel zeigt. Diese Seite sollte den Titel Raumbelegung erhalten und nur für eingeloggte Benutzer sichtbar sein (wie auch /intranet/raumbelegung/woche )
Verstehst du, was ich meine?
