### ISSUE TITLE
Agenda erstellen

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#8]
Wird ein neuer Eintrag mit einem zu diesem Zeitpunkt bereits belegten Raum angelegt, kann dieser nicht gespeichert werden. Bei überlagernder Belegung eines Raums muss gewarnt werden. Es muss aber möglich sein, diese dennoch zu erstellen (z.B. Jungschar-Gottesdienst einmal als Bezirks- und einmal als Junschi-Anlass).

**Comment by bernhard-rohrer** [comment]
Das Problem besteht immer noch oder wieder.

**Comment by szeberli** [comment]
@bernhard-rohrer 
Die Doppelbelegung wird wie folgt gesteuert:
- Datum + Zeit + Raum müssen identisch sein -> dann kommt die Fehlermeldung dass dieser Raum bereits gebucht ist.
- Wenn der Raum nicht identisch ist, dann kann der Anlass erfasst werden.
