### ISSUE TITLE
Monatsansicht bei Raumreservation

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#80]
Falls es einfach möglich ist, würde es uns helfen, wenn man neben der Liste und Woche (oder statt Woche) auch eine Monatsansicht der Raumbelegung ansehen könnte. Also bei uns auf der Seite: https://egwspiez.ch/intranet/raumreservation

Liebe Grüsse
Thomas

**Comment by bernhard-rohrer** [comment]
Für mich ist einfach zentral, dass sich überlagernde Termine nebeneinander und nicht untereinander dargestellt werden.
