### ISSUE TITLE
Serientermine in Agenda

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#81]
Uns würde die Funktion zum Erfassen von Terminserien (wie es auf der alten Homepage möglich war) sehr dienen, da wir viele wöchentlich wiederholte Vermietungen haben. Ist es möglich dies Funktion wieder einzubauen?

**Comment by szeberli** [comment]
Leider ist dieses Feature im Zusammenhang mit ICAL Schnittstelle nicht möglich. 
das die ical Schnittstelle nicht mit wiederkehrenden Terminen umgehenen kann.
Dafür gibt es die Möglichkeit -> den Inhalt zu Clonen. dies sollte einiges vereinfachen.
