### ISSUE TITLE
"Pfarrer" als freies Feld bei Podcasts?

### ISSUE THREAD

**Issue by thoesch** [szeberli/EGW-Webseite#82]
Wenn wir einen neuen Podcast hinzufügen, wäre es hilfreich, wenn beim Feld "Pfarrer" ein freier Eintrag möglich ist und nicht nur vorerfasste Nutzer gewählt werden. Sonst muss für jeden Gastprediger eine Nutzer erstellt werden.

Jetzt kann man zwar frei reinschreiben, aber bei einem nichterfassten Nutzer folt die Meldung: "Es gibt keine Entitäten, die mit „xyz“ übereinstimmen."

Liebe Grüsse
Thomas

**Comment by szeberli** [comment]
@thoesch wird beim nächsten Deploy angepasst.
