### ISSUE TITLE
Zusätzliche Benutzer-Rolle "Dienstplan"

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#84]
Es wäre praktisch, eine Benutzer-Rolle "Dienstplan" zu haben, welche in den die Felder der Gruppe "Dienste" bearbeiten kann. So könnten die Dienstgruppen nicht die öffentlichen Elemente der Agenda verändern.

**Comment by szeberli** [comment]
@bernhard-rohrer 
wird beim nächsten Deploy angepasst:
Die Rolle Agenda Creator -> kann Dienste verwalten
Angemeldete Benutzer können einfach Agenda Einträge hinzufügen ohne Dienste.
![grafik](https://user-images.githubusercontent.com/10152825/114527534-6326d600-9c48-11eb-94b4-4f7372d2f83a.png)

**Comment by bernhard-rohrer** [comment]
Hallo Simon,
Das ist eigentlich genau das umgekehrte von dem, was ich wollte. Wennschon sollten "Angemeldete Benutzer" ihre Dienste bearbeiten können, ohne das sie selber Agendaeinträge erstellen oder verändern können.

**Comment by szeberli** [comment]
Hallo @bernhard-rohrer 
Vohher konnten alle "Angemeldete Benutzer" den Dienstplan anpassen und alle Dienste anpassen. 
Die Rolle Agenda Creator war bereits bestand.
Geändert wurde, dass die Rolle "Agenda Creator" Diensta erstellen / Anpassen kann.

**Comment by szeberli** [comment]
@bernhard-rohrer wie besprochen:
Angemeldete Benutzer -> hat Rechte zum Dienstplan Bearbeiten
Agenda Creator -> Agenda Node erstellen
