### ISSUE TITLE
Doppelte Raumbelegung bei Diensplan Duplizieren

### ISSUE THREAD

**Issue by bernhard-rohrer** [szeberli/EGW-Webseite#9]
Wird ein Eintrag im Dienstplan dupliziert und zu einem Zeitpunkt verschoben, welcher zu einer Doppelbelegung eines Raums führt, wird beim speichern nicht gewarnt.

**Comment by bernhard-rohrer** [comment]
Das Problem besteht immer noch oder wieder.

**Comment by szeberli** [comment]
@bernhard-rohrer 
das kann ich vom Module nicht mit vernünftigen aufwand einbauen...
darf ich das Ticket schliessen?
