### ISSUE TITLE
Losungen block nicht aktuell

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#93]
Im "Losungen block" wird nicht die aktuelle Tageslosung (vom 26.5.) angezeigt, sondern die vom letzten Sonntag (23.5.). 
Ich würde die Tageslosung erwarten.

**Comment by wermelst** [comment]
Scheint mittlerweile aktualisiert worden zu sein. Jetzt steht die aktuelle Tageslosung da.

**Comment by wermelst** [comment]
Jetzt wird überhaupt keine Losung mehr angezeigt...

**Comment by szeberli** [comment]
@wermelst 
kannst du mir deinen link angeben?
