### ISSUE TITLE
Dienstplan: Moderation hinzufügen

### ISSUE THREAD

**Issue by wermelst** [szeberli/EGW-Webseite#96]
Für uns wäre es praktisch, wenn es im Dienstplan auch die Spalte der "Moderation" gibt. Wäre das möglich?
Grund: Wenn wir den Dienstplan exportieren wollen (copy&paste) bräuchten wir auch diese Information.

**Comment by szeberli** [comment]
@wermelst Sobald du einen Diesnt bei Moderation ergänzt, wird auch die Spalte angezeigt.
der Dienstplan ist so gebaut, dass spalten ohne Inhalten nicht angezeigt werden ;)

**Comment by wermelst** [comment]
Ah ja! Perfekt 👍
